import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {eligiblePassages,lexicalRank,hybridRank,cohortTool,ruleTool,validateCitations,validateGraph,SCHEMAS,validateShape} from '../server/core.mjs';
const scope={window:{}};vm.runInNewContext(fs.readFileSync('public/corpus-data.js','utf8'),scope);const corpus=scope.window.CORPUS;
const worker=(await import('../dist/server/index.js')).default;
class Bucket{constructor(){this.rows=new Map();}async get(key){const r=this.rows.get(key);return r?{etag:r.etag,json:async()=>JSON.parse(r.value)}:null;}async put(key,value,options={}){const old=this.rows.get(key);if(options.onlyIf?.etagMatches&&old?.etag!==options.onlyIf.etagMatches)return null;const etag=crypto.randomUUID();this.rows.set(key,{value,etag,customMetadata:options.customMetadata});return {etag};}async list({prefix}){return {objects:[...this.rows].filter(([k])=>k.startsWith(prefix)).map(([key,v])=>({key,customMetadata:v.customMetadata})),truncated:false};}}
const source=['N01§1'];
const outputs={
 context:{summary:'Synthetic context',facts:[{label:'Mandate',value:'250m',status:'Proposed',sources:source}],conflicts:[],questions:['Confirm scope'],searches:[{issue:'Reporting',query:'weekly CHF attribution accepted holdings early clarification'},{issue:'Restrictions',query:'tobacco threshold five percent'},{issue:'Sequence',query:'transfer derivatives readiness'}]},
 precedent:{summary:'Compare issue-level evidence',comparisons:[{case_id:'H01',issue:'Reporting',similarity:'Reporting request',difference:'Custodian',lesson:'Clarify scope',limitation:'Not proof of present capability',sources:source}],rejected:[],gaps:[]},
 risk:{summary:'Watch areas',risks:[{id:'R1',title:'Reporting',attention:'High',trigger:'Requested service',inference:'Potential rework',counterevidence:'Early prevention',action:'Confirm service',owner:'Client Reporting',uncertainty:'Account validation',sources:source}]},
 restriction:{summary:'Interpretation pending',comparisons:[{clause:'Tobacco',difference:'Boundary operator',proposed_wording:'For human review',human_decision:'Confirm intent',sources:source}],questions:['Define coal'],test_notes:['Missing data is review']},
 playbook:{summary:'Proposed workflow',tasks:['Intake','Paperwork','Operational setup','Funding','Post-funding'].map((phase,i)=>({id:'T'+i,phase,action:'Review '+phase,owner:'GCS Operations',reason:'Readiness',depends_on:i?['T'+(i-1)]:[],risk_ids:['R1'],proposed_window:'Proposed',human_gate:'Confirm scope and readiness',sources:source})),route_options:[],changes:[],unresolved_decisions:['Legal interpretation']},
 review:{summary:'Human review required',findings:[{claim:'Planning only',verdict:'Needs human decision',explanation:'Owner review required',sources:source}],ready_for_human_review:true,limitations:['Synthetic records']}
};
test('snapshot, exact boundary, cohort, and dependency controls',()=>{const p=eligiblePassages(corpus,'initial');assert.equal(new Set(p.map(x=>x.document_id)).size,51);assert(!p.some(x=>x.document_id==='O02'||x.document_id==='N07'||x.document_id==='N08'));assert(eligiblePassages(corpus,'cash').some(x=>x.document_id==='N08'));const c=cohortTool(corpus);assert.equal(c.affected,4);assert.equal(c.total,5);assert.equal(c.affected_median_days,10);assert.equal(ruleTool().tests[1].greater_than_5,'PASS');assert.equal(ruleTool().tests[1].at_least_5,'EXCLUDE');assert.equal(ruleTool().tests[3].at_least_5,'REVIEW');assert(lexicalRank(p,'CHF attribution').length>0);assert.equal(validateGraph(outputs.playbook.tasks).length,0);assert(validateGraph([{...outputs.playbook.tasks[0],depends_on:['T0']}]).some(x=>x.includes('cycle')));assert(validateCitations({sources:['N07§1']},p).length>0);assert.equal(validateShape(outputs.risk,SCHEMAS.risk).length,0);});
test('hybrid ranking filters first and combines independently ranked candidates',()=>{const passages=[{id:'a',heading:'',text:'custodian transfer'},{id:'b',heading:'',text:'in-kind transition'}];const hits=hybridRank(passages,'custodian transfer',[0,1],{a:[1,0],b:[0,1]},2);assert.equal(hits.length,2);assert.equal(hits.find(x=>x.id==='a').keyword_rank,1);assert.equal(hits.find(x=>x.id==='b').semantic_rank,1);});
test('real API plumbing with stubbed OpenAI: durable gates, evidence, parallel roles, revisions and ownership',async()=>{
 const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);calls.push({url,body});if(url.endsWith('/embeddings'))return Response.json({data:body.input.map((t,index)=>({index,embedding:Array.from({length:512},(_,i)=>(t.charCodeAt(i%t.length)||1)/1000)})),usage:{total_tokens:100}});const role=body.text.format.name.replace('sa_','');return Response.json({id:'stub-'+role,status:'completed',model:'stub-model',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(outputs[role])}]}],usage:{input_tokens:100,output_tokens:100}});};
 const env={BUCKET:new Bucket(),OPENAI_API_KEY:'test-placeholder-not-a-key'};const call=async(path,data,user='user-a')=>{const req=new Request('https://example.test/api/live/'+path,{method:data?'POST':'GET',headers:{'oai-authenticated-user-id':user,'oai-authenticated-user-email':'reviewer@example.test',...(data?{'Origin':'https://example.test','Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const res=await worker.fetch(req,env);return {status:res.status,data:await res.json()};};
 try{
 let r=(await call('runs',{scenario:'initial',amendment:''})).data;const id=r.id;
 r=(await call('runs/'+id+'/advance',{revision:1})).data;assert.equal(r.gate,'context');assert.equal((await call('runs/'+id+'/advance',{revision:1})).status,409);
 r=(await call('runs/'+id+'/decision',{revision:1,note:'Reviewed the proposed context'})).data;
 for(let i=0;i<4;i++){r=(await call('runs/'+id+'/advance',{revision:1})).data;assert.equal(r.error,null);}
 assert.equal(r.gate,'plan');assert.equal(r.calls.length,6);assert(r.retrievals.length>0);assert(r.retrievals.every(q=>q.results.every(h=>h.passage.date<='2026-09-14'&&h.passage.document_id!=='O02')));
 const starts=r.events.filter(e=>e.type==='agent.started');assert.equal(starts.length,6);const a3=r.events.findIndex(e=>e.agent==='A3'&&e.type==='agent.started'),a4=r.events.findIndex(e=>e.agent==='A4'&&e.type==='agent.started'),a3done=r.events.findIndex(e=>e.agent==='A3'&&e.type==='agent.completed');assert(a3<a4&&a4<a3done);
 assert(calls.filter(x=>x.url.endsWith('/responses')).every(x=>!x.body.input.includes('N07§')&&!x.body.input.includes('N08§')));
 r=(await call('runs/'+id+'/decision',{revision:1,note:'Working plan reviewed; specialist decisions remain'})).data;assert.equal(r.stage,'complete');assert.equal(r.decisions.length,2);
 assert.equal((await call('runs/'+id,null,'user-b')).status,404);
 r=(await call('runs/'+id+'/revise',{revision:1,kind:'amendment',scenario:'clarified',text:'Client confirms Tuesday holdings and monthly analytics.'})).data;assert.equal(r.revision,2);assert.equal(r.history.length,1);assert.equal(r.history[0].decisions.length,2);assert.equal(r.stage,'context');assert.equal(r.gate,null);assert.equal((await call('runs/'+id+'/decision',{revision:1,note:'Stale approval'})).status,409);
 r=(await call('runs/'+id+'/advance',{revision:2})).data;assert.equal(r.gate,'context');assert(r.evidence.some(p=>p.document_id==='N07'));assert(!r.evidence.some(p=>p.document_id==='N08'));
 const noKey=await worker.fetch(new Request('https://example.test/api/live/runs',{method:'POST',headers:{'oai-authenticated-user-id':'user-a',Origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify({scenario:'initial',amendment:''})}),{BUCKET:env.BUCKET});assert.equal(noKey.status,503);
 const anon=await worker.fetch(new Request('https://example.test/api/live/status'),env);assert.equal(anon.status,401);
 const cross=await worker.fetch(new Request('https://example.test/api/live/runs',{method:'POST',headers:{'oai-authenticated-user-id':'user-a',Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'}),env);assert.equal(cross.status,403);
 }finally{globalThis.fetch=original;}
});
