import {SNAPSHOTS,ROLES,SCHEMAS,CONTRACT,INSTRUCTIONS,eligiblePassages,hybridRank,cohortTool,ruleTool,validateShape,validateCitations,validateGraph,initialRun} from './core.mjs';

class AppError extends Error {constructor(message,status=400){super(message);this.status=status;}}
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const modelName=env=>env.OPENAI_MODEL||'gpt-6-astra';
const embeddingName=env=>env.OPENAI_EMBEDDING_MODEL||'text-embedding-3-small';
const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),v=>v.toString(16).padStart(2,'0')).join('');
function requireReady(env){if(!env.OPENAI_API_KEY)throw new AppError('OpenAI connection is not configured. Finish the OpenAI Developers connection so the site owner can configure the backend secret.',503);if(!env.BUCKET)throw new AppError('Run storage is unavailable. Your input has not been submitted to OpenAI.',503);}
async function body(request){const text=await request.text();if(text.length>14000)throw new AppError('Please keep the amendment under 6,000 characters.',413);try{return JSON.parse(text||'{}');}catch{throw new AppError('Invalid request body');}}
async function api(env,path,payload){let response;try{response=await fetch('https://api.openai.com/v1/'+path,{method:'POST',headers:{Authorization:'Bearer '+env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(110000)});}catch{throw new AppError('OpenAI did not complete this request. The run is saved; retry the current step.',502);}if(!response.ok){const code=response.status;await response.text();throw new AppError(code===401||code===403?'OpenAI rejected the configured credentials or model access.':code===429?'OpenAI rate or usage limit reached. The run is saved; retry later.':`OpenAI request failed (${code}). The run is saved; retry this step.`,502);}return response.json();}
function emit(r,type,message,agent=null){r.events.push({id:r.events.length+1,type,message,agent,at:new Date().toISOString()});r.updated_at=new Date().toISOString();}
async function readRun(env,key){const o=await env.BUCKET.get(key);if(!o)throw new AppError('Run not found.',404);return {r:await o.json(),etag:o.etag};}
async function writeRun(env,key,r,etag){r.updated_at=new Date().toISOString();const result=await env.BUCKET.put(key,JSON.stringify(r),{...(etag?{onlyIf:{etagMatches:etag}}:{}),httpMetadata:{contentType:'application/json'},customMetadata:{id:r.id,stage:r.stage,scenario:r.scenario,updated_at:r.updated_at}});if(!result)throw new AppError('This run changed in another request. Refresh the saved run before continuing.',409);return result.etag;}
function baseEvidence(r){return eligiblePassages(CORPUS,r.scenario).filter(p=>p.document_id.startsWith('N')||p.document_id.startsWith('O')).concat(r.amendments.map(a=>({id:a.id,heading:a.kind,text:a.text,document_id:a.id,title:'Human supplied demo amendment',case_id:'NEW',date:r.as_of,version:String(r.revision),status:'hypothetical',kind:a.kind})));}
function allAllowed(r){return eligiblePassages(CORPUS,r.scenario).concat(baseEvidence(r).filter(p=>p.id.startsWith('U')));}
async function embed(env,input){const d=await api(env,'embeddings',{model:embeddingName(env),input,dimensions:512,encoding_format:'float'});if(!Array.isArray(d.data)||d.data.length!==input.length)throw new AppError('Embedding response was incomplete. No search result has been accepted.',502);const rows=d.data.slice().sort((a,b)=>a.index-b.index).map(x=>x.embedding);if(rows.some(x=>!Array.isArray(x)||x.length!==512||x.some(v=>!Number.isFinite(v))))throw new AppError('Invalid embedding data.',502);return {vectors:rows,usage:d.usage};}
async function vectorIndex(env,r,checkpoint){const passages=eligiblePassages(CORPUS,r.scenario),indexKey='indexes/'+CORPUS_HASH+'/'+embeddingName(env)+'/'+r.scenario+'.json',old=await env.BUCKET.get(indexKey);if(old){const d=await old.json();if(d.corpus_hash===CORPUS_HASH&&passages.every(p=>Array.isArray(d.vectors[p.id]))){emit(r,'index.reused',`Reused stored OpenAI embeddings for ${passages.length} eligible passages.`,'A2');await checkpoint();return d.vectors;}}
 emit(r,'embedding.started',`Generating OpenAI embeddings for ${passages.length} eligible source passages.`,'A2');await checkpoint();const result=await embed(env,passages.map(p=>p.title+'\n'+p.heading+'\n'+p.text));const vectors=Object.fromEntries(passages.map((p,i)=>[p.id,result.vectors[i]]));await env.BUCKET.put(indexKey,JSON.stringify({corpus_hash:CORPUS_HASH,model:embeddingName(env),vectors,usage:result.usage,created_at:new Date().toISOString()}),{httpMetadata:{contentType:'application/json'}});emit(r,'embedding.completed',`Indexed ${passages.length} passages; embeddings are cached for this evidence snapshot.`,'A2');await checkpoint();return vectors;}
async function search(env,r,queries,checkpoint){const passages=eligiblePassages(CORPUS,r.scenario),vectors=await vectorIndex(env,r,checkpoint);emit(r,'retrieval.started',`Searching ${queries.length} questions with OpenAI embeddings and keyword ranking.`,'A2');await checkpoint();const embedded=await embed(env,queries.map(q=>q.query));const results=queries.map((q,i)=>({...q,method:'OpenAI embeddings + BM25-style keyword ranking + reciprocal rank fusion',results:hybridRank(passages,q.query,embedded.vectors[i],vectors)}));r.retrievals=results;const ids=new Set(results.flatMap(q=>q.results.map(x=>x.id))),caseIds=new Set(results.flatMap(q=>q.results.slice(0,4).map(x=>x.passage.case_id)).filter(x=>/^H\d+$/.test(x)));const evidence=baseEvidence(r).concat(passages.filter(p=>ids.has(p.id)||caseIds.has(p.case_id)));r.evidence=[...new Map(evidence.map(p=>[p.id,p])).values()];emit(r,'retrieval.completed',`Retrieved ${ids.size} distinct passages; expanded linked case records to ${r.evidence.length} evidence passages.`,'A2');await checkpoint();return results;}
async function generate(env,r,role,input,evidence,checkpoint){const agent='A'+({context:1,precedent:2,risk:3,restriction:4,playbook:5,review:6}[role]);emit(r,'agent.started',`${ROLES[Number(agent.slice(1))-1]} agent called OpenAI.`,agent);await checkpoint();const started=Date.now();const d=await api(env,'responses',{model:r.model,store:false,instructions:CONTRACT+'\n\n'+INSTRUCTIONS[role],input:JSON.stringify({snapshot:r.as_of,revision:r.revision,role,human_challenge:r.challenge,...input,evidence}),text:{format:{type:'json_schema',name:'sa_'+role,schema:SCHEMAS[role],strict:true}},max_output_tokens:7500});
 if(d.status&&d.status!=='completed')throw new AppError('The '+role+' response was incomplete. No completed artifact was accepted.',502);const text=(d.output||[]).flatMap(i=>i.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('');let output;try{output=JSON.parse(text);}catch{throw new AppError('The '+role+' agent did not return a complete structured result.',502);}const errors=[...validateShape(output,SCHEMAS[role]),...validateCitations(output,evidence)];if(role==='playbook'){errors.push(...validateGraph(output.tasks||[]));const known=new Set((r.outputs.risk?.risks||[]).map(x=>x.id));for(const t of output.tasks||[])for(const id of t.risk_ids)if(!known.has(id))errors.push('Unknown risk link '+id);}if(errors.length){r.validation=errors;emit(r,'validation.failed',errors.slice(0,3).join('; '),agent);await checkpoint();throw new AppError('The '+role+' output failed validation. Review the findings and retry this step.',422);}r.calls??=[];r.calls.push({agent,response_id:d.id,model:d.model||r.model,elapsed_ms:Date.now()-started,usage:d.usage,revision:r.revision});emit(r,'agent.completed',`${ROLES[Number(agent.slice(1))-1]} output passed source and structure checks.`,agent);await checkpoint();return output;}
async function advance(env,key,loaded){const r=loaded.r;if(r.busy&&r.lease_until>Date.now())throw new AppError('This step is already running. Its latest status will appear shortly.',409);if(r.gate||r.stage==='complete')throw new AppError('Human review is required before this run can continue.',409);r.busy=true;r.lease_until=Date.now()+300000;r.error=null;r.validation=[];let etag=await writeRun(env,key,r,loaded.etag);let sequence=Promise.resolve();const checkpoint=()=>{sequence=sequence.then(async()=>{etag=await writeRun(env,key,r,etag);});return sequence;};
 try{if(r.stage==='context'){r.evidence=baseEvidence(r);r.outputs.context=await generate(env,r,'context',{amendments:r.amendments},r.evidence,checkpoint);r.gate='context';r.stage='awaiting_context';emit(r,'review.required','Confirm or correct the extracted client context before historical analysis.');}
 else if(r.stage==='precedent'){const q=r.outputs.context.searches.slice(0,4).map(x=>({issue:x.issue,query:x.query.slice(0,350)}));q.push({issue:'Successful prevention and counterevidence',query:'successful early agreement accepted reporting scope no rework preventive action'});if(r.challenge)q.push({issue:'Human challenge',query:r.challenge.slice(0,400)});await search(env,r,q,checkpoint);r.outputs.precedent=await generate(env,r,'precedent',{context:r.outputs.context,retrievals:r.retrievals.map(q=>({issue:q.issue,query:q.query,ranked_passage_ids:q.results.map(x=>x.id)}))},r.evidence,checkpoint);r.stage='analysis';}
 else if(r.stage==='analysis'){r.tools={cohort:cohortTool(CORPUS),rule_tests:ruleTool()};emit(r,'tool.completed','Calculated historical cohort and tobacco boundary cases in code.');await checkpoint();const input={context:r.outputs.context,precedents:r.outputs.precedent,deterministic_tools:r.tools};const results=await Promise.allSettled([generate(env,r,'risk',input,r.evidence,checkpoint).then(x=>{r.outputs.risk=x;}),generate(env,r,'restriction',input,r.evidence,checkpoint).then(x=>{r.outputs.restriction=x;})]);const failed=results.find(x=>x.status==='rejected');if(failed)throw failed.reason;r.stage='playbook';}
 else if(r.stage==='playbook'){r.outputs.playbook=await generate(env,r,'playbook',{context:r.outputs.context,precedents:r.outputs.precedent,risks:r.outputs.risk,restrictions:r.outputs.restriction,prior_plan:r.history.at(-1)?.outputs?.playbook||null},r.evidence,checkpoint);r.stage='review';}
 else if(r.stage==='review'){r.outputs.review=await generate(env,r,'review',{generated_outputs:r.outputs,deterministic_tools:r.tools,graph_validation:validateGraph(r.outputs.playbook.tasks)},r.evidence,checkpoint);if(r.outputs.review.findings.some(f=>f.verdict==='Correction required'))r.outputs.review.ready_for_human_review=false;r.stage='awaiting_plan';r.gate=r.outputs.review.ready_for_human_review?'plan':'correction';emit(r,'review.required',r.gate==='plan'?'Review the proposed plan and record your decision.':'The evidence reviewer found corrections. Challenge or revise the draft before accepting.');}
 else throw new AppError('Unknown run stage',409);
 }catch(e){r.error=e.message||'The current step failed.';emit(r,'run.error',r.error);}
 r.busy=false;r.lease_until=0;await checkpoint();return r;}
function archive(r){r.history.push({revision:r.revision,scenario:r.scenario,as_of:r.as_of,outputs:r.outputs,decisions:r.decisions.filter(d=>d.revision===r.revision),evidence:r.evidence});r.revision++;r.rounds++;r.outputs={};r.retrievals=[];r.evidence=[];r.validation=[];r.error=null;r.gate=null;r.busy=false;r.stage='context';}
async function route(request,env){const u=new URL(request.url);if(!u.pathname.startsWith('/api/live/')){if(!env.ASSETS)return new Response('Site assets unavailable',{status:503});return env.ASSETS.fetch(request);}
 const actor=request.headers.get('oai-authenticated-user-id');if(!actor)throw new AppError('Sign in to this private site to use the live workspace.',401);if(request.method!=='GET'&&request.method!=='HEAD'){if(request.headers.get('origin')!==u.origin||request.headers.get('sec-fetch-site')==='cross-site')throw new AppError('Cross-site request rejected.',403);if(!request.headers.get('content-type')?.includes('application/json'))throw new AppError('JSON request required.',415);}
 const owner=await digest(actor),prefix='runs/'+owner+'/',path=u.pathname.slice('/api/live/'.length);
 if(path==='status'&&request.method==='GET')return json({configured:!!env.OPENAI_API_KEY,storage_ready:!!env.BUCKET,model:modelName(env),embedding_model:embeddingName(env),corpus_documents:CORPUS.document_count,corpus_passages:CORPUS.chunk_count,mode:'Live model calls on synthetic evidence',message:env.OPENAI_API_KEY?'Model credentials configured; the first run verifies access.':'OpenAI connection required before live analysis can run.'});
 if(!env.BUCKET)throw new AppError('Run storage is unavailable.',503);
 if(path==='runs'&&request.method==='GET'){const d=await env.BUCKET.list({prefix,limit:100,include:['customMetadata']});return json({runs:d.objects.map(x=>({...x.customMetadata})).sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||'')),truncated:d.truncated});}
 if(path==='runs'&&request.method==='POST'){requireReady(env);const b=await body(request);if(!SNAPSHOTS[b.scenario])throw new AppError('Choose a valid evidence snapshot.');if(typeof b.amendment!=='string'||b.amendment.length>6000)throw new AppError('Invalid client amendment.');const r=initialRun(b.scenario,b.amendment.trim(),modelName(env));emit(r,'run.created','Created a fresh OpenAI analysis run. Synthetic sources only.');await writeRun(env,prefix+r.id+'.json',r);return json(r,201);}
 const m=path.match(/^runs\/([a-f0-9-]{36})(?:\/(advance|decision|revise|export))?$/);if(!m)throw new AppError('Endpoint not found',404);const key=prefix+m[1]+'.json',loaded=await readRun(env,key),r=loaded.r,action=m[2];
 if((!action||action==='export')&&request.method==='GET')return json(r);
 if(request.method!=='POST')throw new AppError('Method not allowed',405);const b=await body(request);if(b.revision!==r.revision)throw new AppError('The reviewed version has changed. Refresh before continuing.',409);
 if(action==='advance'){requireReady(env);return json(await advance(env,key,loaded));}
 if(r.busy&&r.lease_until>Date.now())throw new AppError('Wait for the running agent step to finish.',409);
 if(action==='decision'){if(typeof b.note!=='string'||b.note.trim().length<5||b.note.length>6000)throw new AppError('Please record a short review rationale.');if(r.gate!=='context'&&r.gate!=='plan')throw new AppError('This draft cannot be accepted in its current state.',409);const kind=r.gate==='context'?'context_confirmed':'planning_draft_accepted';r.decisions.push({id:crypto.randomUUID(),revision:r.revision,kind,actor,display_name:request.headers.get('oai-authenticated-user-email')||'Signed-in reviewer',note:b.note.trim(),at:new Date().toISOString(),artifact_hash:await digest(JSON.stringify(r.outputs)),scope:'Demo planning review only; specialist and execution approvals remain separate'});r.stage=r.gate==='context'?'precedent':'complete';r.gate=null;r.busy=false;emit(r,'human.decision',b.note.trim());await writeRun(env,key,r,loaded.etag);return json(r);}
 if(action==='revise'){requireReady(env);if(r.rounds>=12)throw new AppError('This run has reached its revision limit. Start a fresh run.');if(typeof b.text!=='string'||b.text.trim().length<5||b.text.length>6000)throw new AppError('Enter a challenge or client amendment.');const next=b.scenario||r.scenario;if(!SNAPSHOTS[next]||SNAPSHOTS[next]<r.as_of)throw new AppError('A revision cannot move evidence backwards. Start a fresh run for an earlier snapshot.');const isChallenge=b.kind==='challenge';archive(r);r.scenario=next;r.as_of=SNAPSHOTS[next];if(isChallenge){r.challenge=b.text.trim();}else{r.amendments.push({id:'U'+String(r.amendments.length+1).padStart(2,'0'),text:b.text.trim(),kind:'User supplied hypothetical amendment'});r.challenge='';}emit(r,'revision.created',`Revision ${r.revision}: ${isChallenge?'human challenge':'new client evidence'}. Previous acceptance belongs to the prior version.`);await writeRun(env,key,r,loaded.etag);return json(r);}
 throw new AppError('Action not found',404);
}
export default {async fetch(request,env){try{return await route(request,env);}catch(e){const status=e instanceof AppError?e.status:503;return json({error:e instanceof AppError?e.message:'The live workspace is temporarily unavailable. Your saved run remains available.'},status);}}};
