/* Prepared agent analysis. Retrieval/arithmetic/state run locally; no model endpoint. */
(function(){
const C=window.CORPUS;
const dates={initial:'2026-09-14',clarified:'2026-09-15',cash:'2026-09-16'};
const stop=new Set('the a an and or to of in for on is with from by at as this that has was are be'.split(' '));
const tokens=s=>(s.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>1&&!stop.has(x));
function eligible(d,s='initial',archived=false){return d.date<=dates[s]&&(archived||d.status!=='superseded');}
function retrieve(q,s='initial',archived=false){
 const docs=C.documents.filter(d=>eligible(d,s,archived));const chunks=docs.flatMap(d=>d.chunks.map(c=>({...c,doc:d})));
 const ts=[...new Set(tokens(q))];const N=chunks.length;const lens=chunks.map(c=>tokens(c.heading+' '+c.text));const avg=lens.reduce((a,b)=>a+b.length,0)/Math.max(1,N);
 return chunks.map((c,i)=>{let score=0,matched=[];for(const t of ts){const tf=lens[i].filter(w=>w===t).length;const df=lens.filter(ws=>ws.includes(t)).length;if(tf){score+=Math.log(1+(N-df+.5)/(df+.5))*tf*2.2/(tf+1.2*(.25+.75*lens[i].length/avg));matched.push(t);}}return {...c,score:Math.round(score*100)/100,matched};}).filter(c=>c.score>0).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,15);
}
function get(id){for(const d of C.documents){const c=d.chunks.find(c=>c.id===id);if(c)return {...c,doc:d};}return null;}
const queries=[
 {id:'service',question:'Does a similar client prove that this reporting request is feasible?',query:'weekly CHF attribution Monday reporting holdings',selected:['N01§2','O01§1','N06§1','H01-S§1','H05-S§1'],why:'Compare requested content, accepted content, delivery time and feed dependencies; geography alone is insufficient.'},
 {id:'restriction',question:'Which prior interpretation helps resolve the tobacco and coal clauses?',query:'tobacco 5 threshold coal extraction missing parent',selected:['N02§1','N03§1','H02-G§1','H02-G§2','H08-G§1','O03§1'],why:'Northbridge is geographically different but closely matches the disputed operator. Cedar Vale offers a coal option, not the current client’s intent.'},
 {id:'sequence',question:'What creates a dependency between guidelines, transfer and launch scope?',query:'transfer missing derivatives staged funding readiness',selected:['N04§2','H03-T§1','H08-G§2','O04§1','O04§2'],why:'Combine a data exception precedent with a staged-launch precedent; neither case is a complete template for this mandate.'}
];
const cases=[
 {id:'H01',use:'Reporting failure mechanism',fit:'Strong service analogue',evidence:['H01-I§2','H01-E§1','H01-S§1'],same:'Swiss pension, CHF, requested weekly attribution, mixed funding and derivatives.',different:'Different custodian and platform; accepted holdings/monthly service does not prove weekly attribution capability.',action:'Validate the actual report definition and feed before committing.'},
 {id:'H04',use:'Interacting workstreams',fit:'Strong sequencing analogue',evidence:['H04-E§1','H04-C§1'],same:'CHF reporting, bespoke restrictions, transferred bonds and derivatives within nine weeks.',different:'Observed workstreams overlapped. The five-day launch movement cannot be estimated by adding individual rework days.',action:'Bring a joint reporting/guideline/transition review into intake.'},
 {id:'H02',use:'Contract-to-rule interpretation',fit:'Strong issue analogue',evidence:['H02-G§1','H02-G§2','H02-G§3'],same:'Exact same >5% versus ≥5% tobacco boundary conflict.',different:'US endowment, USD, cash-funded; no Swiss or coal precedent.',action:'Reuse the comparison and boundary-test pattern; obtain new-client interpretation.'},
 {id:'H03',use:'Staged scope option',fit:'Conditional analogue',evidence:['H03-T§1','H03-T§2'],same:'In-kind disposition and derivatives readiness affected the launch route.',different:'Insurance investment objectives, currency and counterparties differ; staging needs a new PM/client decision.',action:'Present a staged route as a decision option with explicit prerequisites.'},
 {id:'H05',use:'Successful preventive action',fit:'Counterevidence',evidence:['H05-S§1','H05-S§2','H05-S§3'],same:'Swiss pension initially requested weekly CHF attribution; no reporting rework.',different:'Service was narrowed in week 1. Cash-only funding and standard guidelines reduce transfer/ESG relevance.',action:'Adopt early scope agreement and sample validation, not a claim that weekly attribution is supported.'},
 {id:'H08',use:'ESG data and coal definition',fit:'Partial issue analogue',evidence:['H08-G§1','H08-G§2','H08-G§3'],same:'Bespoke ESG terms, parent mapping, missing fields and transferred securities.',different:'Its ≥10% extraction-only coal definition was negotiated for that client; not transferable authority.',action:'Ask the client to define coal involvement; preserve unknown data for review.'},
 {id:'H11',use:'Comparison boundary',fit:'Rejected as primary analogue',evidence:['H11-I§2'],same:'Institutional separate-account onboarding.',different:'Global equities, USD monthly reporting, cash funding and standard restrictions do not explain the current risk mechanisms.',action:'Retain in the corpus; do not use as support for this workflow.'}
];
function cohort(excluded=[]){const members=C.historical_cases.filter(h=>!excluded.includes(h.id)&&h.strategy==='Global IG bonds'&&h.currency==='CHF'&&h.reporting==='Weekly attribution');const affected=members.filter(h=>h.events.reporting>0);const days=affected.map(h=>h.events.reporting).sort((a,b)=>a-b);return {ids:members.map(h=>h.id),affected:affected.map(h=>h.id),n:members.length,k:affected.length,median:days.length?(days[Math.floor((days.length-1)/2)]+days[Math.floor(days.length/2)])/2:null};}
function risks(s='initial',excluded=[]){const co=cohort(excluded);return [
 {id:'R1',title:'Reporting promise exceeds supported service',status:s==='initial'?'High attention':'Reduced — validation remains',type:s==='initial'?'Known capability mismatch + anticipated rework':'Changed requirement + remaining dependency',fact:s==='initial'?'N01/N02 request Monday weekly analytics. O01 supports Tuesday holdings and monthly analytics; N06 supplies positions only.':'N07 narrows the request to supported service definitions. The unsigned IMA still needs amendment and the account-specific sample is unvalidated.',inference:s==='initial'?'Without early service negotiation, annex revision and downstream reporting setup are likely to be repeated. Launch impact remains unquantified.':'The original content/cadence mismatch is reduced. A feed rehearsal and annex alignment still determine whether the service can be accepted.',evidence:s==='initial'?['N01§2','N02§3','O01§1','N06§1','H01-E§1']:['N07§1','N07§2','N02§3','O01§1','N06§2'],counter:['H05-S§1','H05-S§2'],action:s==='initial'?'Client Reporting + RM: propose Tuesday holdings/monthly analytics or request a bespoke feasibility assessment; bring the decision into intake.':'Legal + Client Reporting: draft the revised annex, reconcile a sample, obtain client acceptance.',uncertainty:'No current capacity model, dated bespoke-service commitment or calibrated launch forecast. Prior successes used a narrowed service.',observed:`${co.k}/${co.n} selected initial requests recorded reporting rework; median ${co.median??'n/a'} business days among affected cases. Selected synthetic sample, not a probability.`,review:'Client Reporting confirms feasibility; client and Legal accept the service terms.'},
 {id:'R2',title:'Policy intent may be coded incorrectly',status:'High attention',type:'Known wording conflict + unresolved interpretation',fact:'IMA says >5% tobacco; policy says ≥5%. “No thermal coal” has no activity definition or threshold. Issuer mapping, provider and data freshness are unspecified.',inference:'Coding immediately could allow an exactly-5% issuer or implement the wrong coal activity. Prior clauses cannot settle the new client’s intent.',evidence:['N02§1','N02§2','N03§1','H02-G§1','H08-G§3','O03§2'],counter:['H07-C§1'],action:'Legal/FI PC/client interpretation workshop before definitive rule coding; prepare operator, scope and data-treatment options with boundary tests.',uncertainty:'Coal may mean any involvement, extraction, generation, a revenue threshold or a named list. ≥10% extraction is only a historical option.',observed:'Northbridge required 8 business days of guideline rework; Juniper recorded 0 after early interpretation. Neither estimates this case’s delay.',review:'Legal and client approve wording; FI PC confirms implementation and validation.'},
 {id:'R3',title:'Unresolved holdings complicate funding',status:s==='cash'?'Removed from inception route':'High attention',type:s==='cash'?'Requirement change':'Conditional transfer exposure',fact:s==='cash'?'N08 proposes all-cash inception and retention of legacy holdings with the outgoing manager.':'N04 identifies 10m at the tobacco boundary, 10m with 12% coal extraction and 10m with missing ESG data.',inference:s==='cash'?'The in-kind screen no longer gates inception under the revised proposal. ESG rules still govern purchases.':'Under the illustrative ≥5% tobacco / ≥10% extraction option, 20m would be excluded and 10m require review. No disposition is authorized.',evidence:s==='cash'?['N08§1','N08§2']:['N04§1','N04§2','N04§3','H03-T§1','H08-G§2'],counter:['H09-C§1'],action:s==='cash'?'Confirm revised funding instructions and PM/client acceptance; remove the in-kind task from the inception path.':'Obtain data and approved definitions; quantify disposition alternatives and request a client/PM decision before transition.',uncertainty:'The illustrative coal rule and cash substitution are unapproved. Indicative values need later reconciliation.',observed:s==='cash'?'The original 30m in-kind illustration is no longer an inception transfer exposure under N08. The new funding proposal is 250m cash.':'Affected illustrative value: 30m / 250m = 12% of proposed NAV. This is conditional exposure, not expected loss.',review:'Client and PM choose disposition; Transition Management validates instructions.'},
 {id:'R4',title:'Derivative readiness may constrain the launch route',status:s==='cash'?'Deferred — separate readiness':'Watch — readiness unconfirmed',type:'Anticipated dependency risk',fact:s==='cash'?'N08 proposes a bond-only start and derivatives at day 30, subject to review and readiness.':'N01 asks for FX forwards and rate futures at inception; no current dated readiness commitment is in the corpus.',inference:s==='cash'?'Derivative preparation can run as a later route, while controls prevent activation before approval. Day 30 remains a proposal.':'Documentation, broker/counterparty setup and operations may become critical-path dependencies. There is no evidence yet that they will be late.',evidence:s==='cash'?['N08§1','O04§2','H03-T§2']:['N01§3','O04§2','H03-T§1'],counter:['H05-E§1','H12-C§1'],action:s==='cash'?'PM/client review investment implications; amend scope; maintain activation controls and a separate readiness decision.':'Obtain readiness dates now; compare full-scope and staged options with PM/client before fixing the sequence.',uncertainty:'No present counterparty lead time or investment-impact assessment. Do not promise the historical staged outcome will recur.',observed:'Seabrook recorded 10 business days of derivative rework; successful cases also exist. No additive launch-delay estimate.',review:'PM/client accept scope; Legal and Operations confirm readiness.'},
 {id:'R5',title:'Country-specific obligations require authoritative review',status:'Evidence gap',type:'Unresolved review need',fact:'The client is Swiss-domiciled. O05 routes it to Legal review but provides no statutory requirements or regulatory corpus.',inference:'The assistant should request the applicable requirements assessment rather than invent a weekly-reporting law or prescribe a tax form.',evidence:['N01§1','O05§1','O05§2'],counter:[],action:'Legal verifies applicable requirements using authoritative current sources in a real onboarding; record the determination as new evidence.',uncertainty:'Jurisdiction, entity classification and service-specific applicability have not been independently assessed in this fictional package.',observed:'No numerical risk estimate supported.',review:'Legal owns applicability and the recorded determination.'}
];}
function workflow(s='initial'){
 let rows=[
 ['T01','Intake','Confirm context and unresolved requirements','GCS Operations','Week 1',[],'Keep the five phases; tailor the route to specific watch areas.',['N01§4','N05§3']],
 ['T02','Intake',s==='initial'?'Agree reporting scope and feasibility':'Record revised reporting scope','Client Reporting + RM','Week 1',['T01'],'Move service definition forward from later reporting setup; avoid repeating annex and configuration work.',s==='initial'?['O01§1','H05-S§1']:['N07§1','H05-S§1']],
 ['T03','Intake','Resolve restriction wording, scope and data semantics','Legal + FI PC + client','Week 1',['T01'],'An exact operator conflict and undefined coal activity must be resolved before coding.',['N02§1','N03§1','H02-G§1','H08-G§3']],
 ['T04','Intake','Verify jurisdiction-specific applicability','Legal','Week 1',['T01'],'Country is a review signal; authoritative requirements are missing.',['O05§2']],
 ['T05','Paperwork','Draft and accept service/guideline annexes','Legal + client','Weeks 1–3',['T02','T03','T04'],'Record mandate-specific decisions; a historical contract cannot authorize this client’s terms.',['N02§4','O03§2']],
 ['T06','Operational setup','Reconcile sample holdings and benchmark inputs','Client Reporting + Results + Custody','Weeks 1–3',['T02'],'Test positions, CHF reporting inputs and benchmark mapping before promising a recurring deliverable.',['N06§1','N06§2','O01§2']],
 ['T07','Operational setup','Review draft rules and run boundary/data tests','FI PC + ESG','Weeks 2–4',['T03'],'Reuse prior testing patterns while retaining client-specific definitions.',['H02-G§2','O03§3']],
 ['T08','Operational setup','Confirm custody, market access and system records','GCS Operations + Custody','Weeks 2–6',['T01'],'Proceed in parallel; preserve Appian/existing-system ownership.',['N05§2','O04§1']],
 ['T09','Operational setup',s==='cash'?'Plan later derivative readiness and activation controls':'Obtain derivative readiness dates and scope options','Operations + Legal + PM','Weeks 1–4',['T01'],'A historical staged route is an option requiring a new investment decision.',['O04§2','H03-T§2']],
 ['T10','Funding','Agree launch scope with accountable humans','GCS Operations + PM + client','Before funding',['T05','T06','T07','T08',...(s==='cash'?[]:['T09','T11'])],'Select a route only after its evidence and dependencies are understood.',['O04§2','O04§3']],
 ['T12','Funding',s==='cash'?'Confirm 250m cash-funding instructions':'Confirm agreed funding mix and dispositions','Transition Management + client','Before funding',['T10',...(s==='cash'?[]:['T11'])],'Validate instructions and values; the assistant does not move assets.',s==='cash'?['N08§1']:['N04§3']],
 ['T13','Post-funding','Validate first reporting cycle and record lessons','Client Reporting + GCS Operations','First agreed cycles',['T12'],'Compare promised versus delivered scope and enrich the case corpus with reviewed outcomes.',['H05-S§1','H01-C§2']]
 ];
 if(s!=='cash')rows.splice(9,0,['T11','Operational setup','Screen indicative transfer and decide exceptions','Transition + FI PC + PM/client','Weeks 2–4',['T03','T07'],'Start the data request early; definitive eligibility requires approved semantics.',['N04§2','N04§3','H08-G§2']]);
 else rows.push(['T14','Post-funding','Review separate derivative activation readiness','PM + Legal + Operations','Proposed day 30; subject to readiness',['T09','T12'],'Do not treat the client’s day-30 proposal as an automatic activation date.',['N08§1','O04§2']]);
 return rows.map(([id,phase,task,owner,timing,depends,why,evidence])=>({id,phase,task,owner,timing,depends,why,evidence,status:'Proposed; human review required'}));
}
const checks=[
 {claim:'A previous Swiss client proves weekly attribution is available.',verdict:'Unsupported',correction:'H05 accepted weekly holdings and monthly analytics. Current O01 governs capability.',evidence:['H05-S§1','O01§1']},
 {claim:'There is an 80% probability that this onboarding will be delayed.',verdict:'Unsupported',correction:'4/5 is reporting-rework incidence in a small selected synthetic cohort, not a calibrated new-client probability or launch-delay forecast.',evidence:['H01-E§3','H04-E§3','H05-E§3','H06-E§3','H10-E§3']},
 {claim:'Swiss regulations require weekly reporting.',verdict:'Unsupported',correction:'The requirement comes from N01. No authoritative regulation evidence is included.',evidence:['N01§2','O05§1']},
 {claim:'Copy Cedar Vale’s coal >=10% rule into Alpenridge.',verdict:'Needs new-client interpretation',correction:'“No thermal coal” is undefined. Extraction-only >=10% is one historical negotiated option, not inferred intent.',evidence:['N02§2','H08-G§1','H08-G§3']},
 {claim:'Add every workstream’s rework days to forecast the launch date.',verdict:'Invalid calculation',correction:'Historical workstreams overlapped. Current dependencies and capacity need owner review.',evidence:['H04-E§1','H04-C§1','O04§3']}
];
function trace(s='initial',excluded=[]){return [
 {id:'A1',name:'Context agent',capability:'Interpret an ambiguous request',input:['N01','N02','N03','N04','N05','N06',...(s!=='initial'?['N07']:[]),...(s==='cash'?['N08']:[])],output:{client:'Alpenridge Pension Foundation',target:'2026-11-23, proposed',questions:['What is requested versus contractually agreed?','Which service components need separate feasibility checks?','Which investment terms remain ambiguous?'],requirements:{reporting:s==='initial'?'Weekly CHF analytics, Monday 08:00':'Weekly CHF holdings Tuesday; monthly analytics',funding:s==='cash'?'250m cash':'200m in-kind + 50m cash',derivatives:s==='cash'?'Proposed later activation':'At inception'},contradictions:['>5% versus ≥5% tobacco','Undefined thermal coal','Unsigned service annex'],evidence:['N01§2','N02§1','N03§1',...(s!=='initial'?['N07§1']:[]),...(s==='cash'?['N08§1']:[])]}},
 {id:'A2',name:'Precedent agent',capability:'Retrieve by issue; compare differences',input:['A1','54-document corpus'],output:{queries:queries.map(q=>({query:q.query,purpose:q.question,lexical_results:retrieve(q.query,s).slice(0,5).map(c=>({chunk:c.id,score:c.score})),prepared_semantic_selection:q.selected})),cases:cases}},
 {id:'A3',name:'Risk agent',capability:'Infer mechanisms and challenge with counterevidence',input:['A1','A2','O01','O03','O04','O05'],output:{risks:risks(s,excluded),cohort:cohort(excluded),forecast_limit:'No calibrated probability or committed completion date.'}},
 {id:'A4',name:'Restriction agent',capability:'Translate intent into reviewable implementation options',input:['N02','N03','H02-G','H08-G','O03','N04'],output:{tobacco_options:['>5% follows the draft; exactly 5% is not excluded.','≥5% follows the client policy; exactly 5% is excluded.'],coal:'Unresolved: activity, operator, threshold, mapping and provider must be decided.',candidate:'Only for illustration after human selection: tobacco >=5; coal extraction >=10; missing or >30-day data => review.',conditional_impact:'20m excluded + 10m review, under that unapproved illustration.',evidence:['H02-G§1','H08-G§3','N04§2','O03§3']}},
 {id:'A5',name:'Playbook agent',capability:'Compose a route from interacting constraints',input:['A1','A3','A4'],output:{tasks:workflow(s),schedule:'Relative planning windows for owner review, not predicted durations.',changes:s==='initial'?['Bring reporting and guideline interpretation into intake.','Run feed testing and readiness discovery in parallel.']:s==='clarified'?['Replace reporting scope negotiation with annex alignment and sample acceptance.','Keep transfer, guideline and derivative decisions.']:['Remove the in-kind screen from the inception route.','Separate later derivative readiness from cash-bond inception.','Keep ESG rule validation for new purchases.']}},
 {id:'A6',name:'Evidence reviewer',capability:'Check authority, unsupported claims and dependencies',input:['A1–A5','cited passages'],output:{checks,decision:'Draft ready for human review; unresolved decisions remain.',automation_boundary:'No external messages, Appian tasks, contract execution or investment instructions.'}}
 ];}
function screen({tobacco,coal,age=0,mapping=true}){
 if(!mapping||tobacco==null||coal==null||age==null||age>30)return 'REVIEW';
 return tobacco>=5||coal>=10?'EXCLUDE':'PASS_ACTIVITY_SCREEN';
}
function ruleChecks(){return [
 {name:'Tobacco below',input:{tobacco:4.99,coal:0},expected:'PASS_ACTIVITY_SCREEN'},
 {name:'Tobacco at',input:{tobacco:5,coal:0},expected:'EXCLUDE'},
 {name:'Tobacco above',input:{tobacco:5.01,coal:0},expected:'EXCLUDE'},
 {name:'Coal below',input:{tobacco:0,coal:9.99},expected:'PASS_ACTIVITY_SCREEN'},
 {name:'Coal at',input:{tobacco:0,coal:10},expected:'EXCLUDE'},
 {name:'Coal above',input:{tobacco:0,coal:10.01},expected:'EXCLUDE'},
 {name:'Missing data',input:{tobacco:null,coal:null},expected:'REVIEW'},
 {name:'Age at boundary',input:{tobacco:0,coal:0,age:30},expected:'PASS_ACTIVITY_SCREEN'},
 {name:'Stale data',input:{tobacco:0,coal:0,age:31},expected:'REVIEW'},
 {name:'Unresolved mapping',input:{tobacco:0,coal:0,mapping:false},expected:'REVIEW'}
 ].map(t=>({...t,actual:screen(t.input)}));}
window.AGENT_DEMO={dates,retrieve,get,eligible,queries,cases,cohort,risks,workflow,trace,checks,screen,ruleChecks};
})();
