const E=window.AGENT_DEMO,C=window.CORPUS;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='sa-corpus-demo-v1';let state={view:'system',scenario:'initial',excluded:[],revision:1,approval:null,notes:[],edits:{},levels:null};
try{Object.assign(state,JSON.parse(localStorage.getItem(key)||'{}'));if(!E.dates[state.scenario])state.scenario='initial';}catch(e){}
function save(){localStorage.setItem(key,JSON.stringify(state));}
function notify(s){const t=document.getElementById('toast');t.textContent=s;t.style.display='block';setTimeout(()=>t.style.display='none',3800);}
function revise(){state.revision++;state.approval=null;save();}
const head=(title,sub,actions='')=>`<div class="pagehead"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;
function showSource(id){const c=E.get(id),d=c?.doc||C.documents.find(d=>d.id===id);if(!d)return;if(d.date>E.dates[state.scenario]){notify('This document is not yet available in the selected scenario.');return;}const m=document.getElementById('modal');m.innerHTML=`<div class="dialoghead"><div><div class="eyebrow">${esc(d.id)} · ${esc(d.kind)} · ${esc(d.status)}</div><h2>${esc(d.title)}</h2><div class="smalltext muted">${esc(d.owner)} · ${esc(d.date)} · v${esc(d.version)}</div></div><button class="btn small" data-close>Close</button></div><div class="dialogbody"><div class="notice">Synthetic source document. This is the underlying passage used in the agent-generated analysis.</div>${d.chunks.map(p=>`<section class="${p.id===id?'selected':''}"><h3>${esc(p.id)} · ${esc(p.heading)}</h3><p>${esc(p.text)}</p></section>`).join('')}<a class="btn" href="${esc(d.path)}" download>Download source file</a></div>`;m.showModal();m.querySelector('.selected')?.scrollIntoView({block:'nearest'});}
let disposeAgentRunner=null,disposeWorkflow=null;
function system(){return window.SA_SYSTEM.frame();}
function animatedRun(){return head('Agent run','Watch the client request move through the six agents. The run pauses after each agent so you can read its output, and every finished output stays on this page.')+window.SA_RUNNER.frame;}
function workflow(){return head('Workflow & risk','Pick Low, Medium or High for each area to see what it means, the onboarding days and who does what.')+window.SA_WORKFLOW.markup;}
const views={system,run:animatedRun,workflow};
const nav=[['system','01','Multi-agent system'],['run','02','Agent run'],['workflow','03','Workflow & risk']];
function render(){if(disposeAgentRunner){disposeAgentRunner();disposeAgentRunner=null;}if(disposeWorkflow){disposeWorkflow();disposeWorkflow=null;}if(!views[state.view])state.view='system';document.getElementById('app').innerHTML=`<div class="shell"><aside class="rail"><div class="brand">Separate Account<br>Navigator<small>Evidence → judgment → route</small></div><nav aria-label="Workspace navigation">${nav.map(([v,n,label])=>`<button class="nav ${v===state.view?'active':''}" data-view="${v}" ${v===state.view?'aria-current="page"':''}><span>${n}</span>${label}</button>`).join('')}</nav><div class="rail-note"><button class="btn small" data-reset>Reset workspace</button></div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">Institutional separate accounts</div><strong>Alpenridge · 250m global bond mandate</strong></div><label class="scenario">Evidence snapshot<select id="scenario">${[['initial','14 Sep · Initial request'],['clarified','15 Sep · Reporting clarified'],['cash','16 Sep · Cash / staged scope']].map(([v,t])=>`<option value="${v}" ${state.scenario===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="method">Agent workflow · Synthetic corpus · Local search and calculations · Human review</div><div class="body">${views[state.view]()}<div class="foot"><details><summary>About this workspace</summary><p>Synthetic client data and agent-generated analysis. Search and calculations run locally; no live model or production systems are connected. Recommendations require human review.</p></details></div></div></main></div>`;
 if(state.view==='workflow'){disposeWorkflow=window.SA_WORKFLOW.mount(document.getElementById('wr-root'),{scenario:state.scenario,levels:state.levels,onLevels:levels=>{state.levels=levels;save();},onScenario:v=>{if(state.scenario!==v){state.scenario=v;state.edits={};revise();log('Loaded evidence snapshot '+E.dates[v]+' from Workflow & risk.');const sel=document.getElementById('scenario');if(sel)sel.value=v;}}});}
 if(state.view==='run'){disposeAgentRunner=window.SA_RUNNER.mount(document.getElementById('agent-runner-root'),{autoStart:Boolean(state.runAutoStart),getContext:()=>({scenario:state.scenario,revision:state.revision,excluded:[...state.excluded],edits:JSON.parse(JSON.stringify(state.edits))}),onScenario:v=>{if(state.scenario!==v){state.scenario=v;state.edits={};state.levels=null;revise();log('New client evidence received: '+E.dates[v]+'. Previous planning acceptance invalidated.');const selector=document.getElementById('scenario');if(selector)selector.value=v;}},onHuman:(message,kind)=>{if(kind==='challenge')revise();log(message);},onAccept:decision=>{state.approval={name:decision.name,role:'GCS Operations',note:decision.note,revision:decision.revision,at:new Date().toISOString()};log(decision.name+' accepted the working draft. '+decision.note);save();}});state.runAutoStart=false;}
 save();}
function log(text){state.notes.push({text,revision:state.revision,at:new Date().toISOString()});save();}
function setScenario(v){if(v===state.scenario)return;state.scenario=v;state.edits={};state.levels=null;revise();log('Changed evidence snapshot to '+E.dates[v]+'. Prior draft acceptance cleared.');render();notify('Evidence snapshot changed. Risk levels and the proposed route were updated.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.close!==undefined){document.getElementById('modal').close();return;}if(d.source){showSource(d.source);return;}if(d.view){state.view=d.view;render();window.scrollTo(0,0);}if(d.start!==undefined){state.runAutoStart=true;state.view='run';render();}if(d.reset!==undefined){localStorage.removeItem(key);location.reload();}});
document.addEventListener('change',e=>{if(e.target.id==='scenario')setScenario(e.target.value);});
render();
