window.SA_RISK_MAP = {
  markup: `
    <div id="sa-route-risk">
      <header class="rr-heading">
        <div>
          <div class="rr-eyebrow">ALPENRIDGE · DECISION PATH</div>
          <h2>See how new evidence changes risk and workflow</h2>
          <p class="rr-intro">Choose a dated client snapshot, then select a risk. The graph highlights the tasks, dependencies and human decisions affected by that risk.</p>
        </div>
        <div class="rr-mandate"><b>$250m</b><span>Global IG bond mandate<br>Swiss pension foundation</span></div>
      </header>
      <section aria-labelledby="rr-snapshot-heading">
        <div class="rr-section-title"><div><span class="rr-step-number">1</span><div><h3 id="rr-snapshot-heading">Choose the evidence snapshot</h3><p>Each column is the same client at a different point in time.</p></div></div><span class="rr-help">Dates show when new evidence arrived</span></div>
        <div class="rr-scenarios" id="rr-scenarios"></div>
      </section>
      <section class="rr-risk-section" aria-labelledby="rr-risk-heading">
        <div class="rr-section-title"><div><span class="rr-step-number">2</span><div><h3 id="rr-risk-heading">Choose the risk to trace</h3><p>Status reflects the selected snapshot. It is an attention level, not a probability.</p></div></div></div>
        <div class="rr-risk-picker" id="rr-risk-picker"></div>
      </section>
      <section class="rr-graph-section" aria-labelledby="rr-graph-title">
        <div class="rr-graph-head">
          <div><span class="rr-step-number">3</span><div><h3 id="rr-graph-title">Dependency graph</h3><p id="rr-graph-subtitle"></p></div></div>
          <div class="rr-legend"><span><i class="rr-legend-line active"></i>Selected risk path</span><span><i class="rr-legend-line"></i>Other dependency</span><span><i class="rr-legend-diamond"></i>Human decision</span></div>
        </div>
        <div class="rr-risk-summary" id="rr-risk-summary"></div>
        <div class="rr-graph-scroll" tabindex="0" aria-label="Scrollable onboarding dependency graph"><div class="rr-graph-canvas" id="rr-graph-canvas"><svg class="rr-edges" id="rr-edges" aria-hidden="true"></svg><div class="rr-columns" id="rr-columns" role="group" aria-label="Onboarding tasks across five phases"></div></div></div>
      </section>
      <section class="rr-evidence" id="rr-evidence" aria-live="polite"></section>
      <footer class="rr-foot"><span>Evidence linked</span><span>Human approval retained</span><span>Plan revises when client facts change</span></footer>
    </div>`,
  mount(options = {}) {
    const root = document.getElementById('sa-route-risk');
    const scenariosRoot = root.querySelector('#rr-scenarios');
    const riskPicker = root.querySelector('#rr-risk-picker');
    const columns = root.querySelector('#rr-columns');
    const canvas = root.querySelector('#rr-graph-canvas');
    const svg = root.querySelector('#rr-edges');
    const evidence = root.querySelector('#rr-evidence');
    const source = Object.fromEntries(window.CORPUS.documents.flatMap(d => d.chunks.map(c => [c.id, [d.title + ' · v' + d.version, c.text]])));
    const scenarios = [
      {id:'initial',date:'14 Sep',label:'Initial request',change:'Starting position',funding:'$200m securities + $50m cash',reporting:'Monday weekly CHF analytics requested',derivatives:'Derivatives requested at launch',delta:'Mixed funding creates transfer dependencies.'},
      {id:'clarified',date:'15 Sep',label:'Reporting clarified',change:'Reporting changed only',funding:'$200m securities + $50m cash',reporting:'Tuesday holdings + monthly analytics accepted',derivatives:'Derivatives still requested at launch',delta:'Reporting falls from High to Lower. Funding is unchanged.'},
      {id:'cash',date:'16 Sep',label:'Cash + later derivatives',change:'Funding and launch scope changed',funding:'$250m cash · no securities transferred',reporting:'Clarified reporting remains in force',derivatives:'Derivatives move to a later approval',delta:'Transfer turns Off. Derivatives become a separate later path.'}
    ];
    const risks = {
      reporting:{name:'Reporting',statuses:['High','Lower','Lower'],levels:['high','lower','lower'],route:['T02','T05','T06','T10','T12','T13'],ai:'Compare the requested service with current operating capability and relevant precedents.',facts:['Monday weekly analytics exceed the current supported service.','The client accepts Tuesday holdings and monthly analytics.','The clarified reporting scope remains in force.'],action:['Negotiate the service during intake and test a sample before commitment.','Update the annex and validate the account-specific custody feed.','Keep annex alignment, feed testing and first-cycle validation.'],human:'Client Reporting validates feasibility; Legal and the client approve the service terms.',refs:[['N01§2','O01§1','H05-S§1'],['N07§1','N06§2','H05-S§1'],['N07§1','N06§2','H05-S§1']],note:'Historical rework makes this an early attention area. The cohort is descriptive evidence, not a calibrated forecast.'},
      restrictions:{name:'Restrictions',statuses:['High','High','High'],levels:['high','high','high'],route:['T03','T05','T07','T11','T10','T12'],ai:'Compare contractual clauses and turn ambiguity into testable interpretation questions.',facts:['IMA uses >5%; policy uses ≥5%; thermal coal is undefined.','The reporting clarification does not change the restriction ambiguity.','Cash funding removes transfer screening, but purchase restrictions still apply.'],action:['Resolve intent before coding or definitive transfer screening.','Keep the Legal and FI PC interpretation workshop.','Approve and test the rules before the portfolio buys securities.'],human:'The client and Legal decide intent; FI PC validates implementation and boundary tests.',refs:[['N02§1','N03§1','H02-G§1','H08-G§3'],['N02§1','N03§1','H08-G§3'],['N03§1','N08§2','H08-G§3']],note:'At exactly 5%, the two tobacco operators produce different results. Cash funding does not remove that issue.'},
      transfer:{name:'In-kind transfer',statuses:['High','High','Off'],levels:['high','high','off'],route:['T03','T07','T11','T08','T10','T12'],ai:'Connect restriction interpretation and missing asset data to the proposed funding route.',facts:['Three $10m positions raise threshold, coal-scope or missing-data questions.','The reporting clarification does not change the proposed securities transfer.','The client proposes all-cash inception; legacy assets stay outside the account.'],action:['Interpret, screen and obtain an explicit disposition decision.','Retain the transfer screen and client/PM disposition review.','Remove in-kind screening from inception and verify cash instructions.'],human:'Client and PM choose the funding route; Transition validates the final instructions.',refs:[['N04§2','N04§3'],['N04§2','N04§3'],['N08§1','N08§2']],note:'Off means removed from this inception route. It returns if the client reintroduces a securities transfer.'},
      derivatives:{name:'Derivatives',statuses:['Watch','Watch','Later'],levels:['watch','watch','later'],route:['T09','T10','T12','T14'],ai:'Compare full-scope and staged routes with the available readiness evidence.',facts:['Day-one derivatives are requested; readiness dates are missing.','The reporting change does not establish derivative readiness.','The client proposes later activation after the cash-bond launch.'],action:['Obtain readiness dates and assess the launch-scope options.','Keep readiness discovery and the PM/client scope decision.','Run a separate readiness path and later activation decision.'],human:'PM and client accept the investment implications; Legal and Operations confirm readiness.',refs:[['O04§2','H03-T§2'],['O04§2','H03-T§2'],['N08§2','O04§2']],note:'Later is a sequencing decision, not approval. A proposed day 30 remains subject to readiness.'},
      legal:{name:'Legal applicability',statuses:['Gap','Gap','Gap'],levels:['gap','gap','gap'],route:['T04','T05','T10'],ai:'Detect that authoritative evidence is missing and route the question to the qualified owner.',facts:['Swiss domicile is known; applicable requirements are not established.','Reporting clarification does not close the legal evidence gap.','The funding change does not close the legal evidence gap.'],action:['Request the Legal applicability determination.','Retain the authoritative requirements review.','Retain the authoritative requirements review.'],human:'Legal determines applicable requirements using current authoritative sources.',refs:[['O05§1','O05§2'],['O05§1','O05§2'],['O05§1','O05§2']],note:'The system does not infer Swiss legal or tax requirements from domicile alone.'}
    };
    const baseTasks = [
      {id:'T02',phase:0,title:'Agree reporting scope',owner:'Client Reporting + RM',deps:[],human:true,refs:['N01§2','O01§1','H05-S§1']},
      {id:'T03',phase:0,title:'Clarify restriction intent',owner:'Legal + FI PC + client',deps:[],human:true,refs:['N02§1','N03§1','H02-G§1']},
      {id:'T04',phase:0,title:'Determine legal applicability',owner:'Legal',deps:[],human:true,refs:['O05§2']},
      {id:'T05',phase:1,title:'Accept mandate annexes',owner:'Legal + client',deps:['T02','T03','T04'],human:true,refs:['N03§1','N05§3']},
      {id:'T06',phase:2,title:'Validate sample feed',owner:'Reporting + Results + Custody',deps:['T02'],human:false,refs:['N06§2','O01§1']},
      {id:'T07',phase:2,title:'Test investment rules',owner:'FI PC + ESG',deps:['T03'],human:false,refs:['H02-G§1','H08-G§3']},
      {id:'T08',phase:2,title:'Confirm custody and systems',owner:'GCS Operations + Custody',deps:[],human:false,refs:['N05§3']},
      {id:'T09',phase:2,title:'Check derivative readiness',owner:'Operations + Legal + PM',deps:[],human:false,refs:['O04§2']},
      {id:'T11',phase:2,title:'Screen transfer and exceptions',owner:'Transition + FI PC + PM/client',deps:['T03','T07'],human:true,refs:['N04§2','N04§3']},
      {id:'T10',phase:3,title:'Agree launch scope',owner:'GCS Operations + PM + client',deps:['T05','T06','T07','T08','T09','T11'],human:true,refs:['O04§2','N05§3']},
      {id:'T12',phase:3,title:'Confirm funding mix',owner:'Transition + client',deps:['T10','T11'],human:true,refs:['N04§3']},
      {id:'T13',phase:4,title:'Validate first reporting cycle',owner:'Client Reporting + Operations',deps:['T12'],human:false,refs:['H05-S§1']},
      {id:'T14',phase:4,title:'Approve later activation',owner:'PM + Legal + Operations',deps:['T09','T12'],human:true,refs:['N08§2','O04§2'],later:true}
    ];
    const phases=[['01','Intake','Resolve client intent'],['02','Paperwork','Record approved terms'],['03','Operational setup','Configure and test'],['04','Funding','Authorize the route'],['05','Post-funding','Validate live operation']];
    const state={scene:Math.max(0,scenarios.findIndex(s=>s.id===options.scenario)),risk:options.risk||'reporting',task:null,source:null};
    const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    function tasks(){const scenario=scenarios[state.scene].id;return baseTasks.filter(t=>!t.later||scenario==='cash').map(t=>{const plan=window.AGENT_DEMO.workflow(scenario).find(p=>p.id===t.id);const edit=options.taskEdits?.[t.id]||{};const x={...t,deps:plan?[...plan.depends]:[...t.deps],refs:plan?[...plan.evidence]:[...t.refs],owner:edit.owner||plan?.owner||t.owner,timing:edit.timing||plan?.timing||''};if(x.id==='T02'&&state.scene>0){x.title='Align clarified reporting';x.refs=['N07§1','N06§2'];}if(scenario==='cash'){if(x.id==='T11'){x.removed=true;x.title='In-kind screen removed';x.deps=[];x.refs=['N08§1','N08§2'];}if(x.id==='T09'){x.title='Prepare later derivatives';x.laterTrack=true;}if(x.id==='T10')x.deps=x.deps.filter(d=>d!=='T09'&&d!=='T11');if(x.id==='T12'){x.title='Confirm $250m cash';x.deps=['T10'];x.refs=['N08§1'];}}return x;});}
    function related(t){if(state.scene===2&&state.risk==='transfer')return['T11','T10','T12'].includes(t.id);if(state.scene===2&&state.risk==='derivatives')return['T09','T12','T14'].includes(t.id);return risks[state.risk].route.includes(t.id);}
    function renderScenarios(){scenariosRoot.innerHTML=scenarios.map((s,i)=>`<button type="button" class="rr-scenario-card ${i===state.scene?'selected':''}" data-scene="${i}" aria-pressed="${i===state.scene}"><span class="rr-scenario-top"><span class="rr-date">${s.date}</span><span class="rr-scenario-kicker">${safe(s.change)}</span></span><strong>${safe(s.label)}</strong><dl><div><dt>Funding</dt><dd>${safe(s.funding)}</dd></div><div><dt>Reporting</dt><dd>${safe(s.reporting)}</dd></div><div><dt>Derivatives</dt><dd>${safe(s.derivatives)}</dd></div></dl><span class="rr-change">${safe(s.delta)}</span></button>`).join('');}
    function renderRisks(){riskPicker.innerHTML=Object.entries(risks).map(([id,r])=>`<button type="button" class="rr-risk-button ${id===state.risk?'selected':''}" data-risk="${id}" aria-pressed="${id===state.risk}"><span>${safe(r.name)}</span><b data-level="${r.levels[state.scene]}">${r.statuses[state.scene]}</b></button>`).join('');}
    function renderGraph(){const s=scenarios[state.scene],r=risks[state.risk],ts=tasks();root.querySelector('#rr-graph-title').textContent=`${r.name} dependency path · ${s.date}`;root.querySelector('#rr-graph-subtitle').textContent=`${s.label}: ${s.funding}`;root.querySelector('#rr-risk-summary').innerHTML=`<div class="rr-summary-status" data-level="${r.levels[state.scene]}"><span>${safe(r.name)}</span><b>${r.statuses[state.scene]}</b></div><div><span class="rr-summary-label">Why this status</span><p>${safe(r.facts[state.scene])}</p></div><div><span class="rr-summary-label">What the plan does</span><p>${safe(r.action[state.scene])}</p></div>`;columns.innerHTML=phases.map((p,phase)=>`<section class="rr-phase ${ts.some(t=>t.phase===phase&&related(t)&&!t.removed)?'active':''}"><header><span>${p[0]}</span><div><h4>${p[1]}</h4><p>${p[2]}</p></div></header><div class="rr-nodes">${ts.filter(t=>t.phase===phase).map(t=>`<article class="rr-node ${related(t)?'relevant':'dimmed'} ${t.removed?'removed':''} ${t.laterTrack||t.later?'later':''}" id="rr-${t.id}"><button type="button" data-task="${t.id}" aria-pressed="${state.task===t.id}"><span class="rr-node-top"><b>${t.id}</b><em>${t.removed?'Removed':t.laterTrack||t.later?'Later track':t.human?'Human decision':'Validation'}</em></span><strong>${safe(t.title)}</strong><span class="rr-owner">${safe(t.owner)}</span><span class="rr-dep-count">${t.deps.length?`${t.deps.length} dependenc${t.deps.length===1?'y':'ies'}`:t.removed?'Not in inception route':'Starts from client context'}</span></button></article>`).join('')}</div></section>`).join('');renderEvidence();requestAnimationFrame(drawEdges);}
    function sourceBlock(refs,src){return `<div class="rr-sources">${refs.map(id=>`<button type="button" class="btn btn-ghost" data-map-source="${id}" aria-pressed="${state.source===id}">${id}</button>`).join('')}</div><blockquote class="rr-quote"><span>${safe(src[0])} · ${safe(state.source)}</span><p>${safe(src[1])}</p></blockquote><button type="button" class="btn small" data-source="${safe(state.source)}">Open full source document</button>`;}
    function renderEvidence(){const r=risks[state.risk],t=tasks().find(x=>x.id===state.task),refs=t?t.refs:r.refs[state.scene];if(!refs.includes(state.source))state.source=refs[0];const src=source[state.source]||['Source record','Source passage unavailable in this snapshot.'];evidence.innerHTML=t?`<div class="rr-detail-head"><div><span class="rr-detail-label">SELECTED TASK</span><h3>${safe(t.id+' · '+t.title)}</h3></div><button type="button" class="btn small" data-clear-task>Back to risk explanation</button></div><div class="rr-task-detail"><div><span>Owner</span><b>${safe(t.owner)}</b></div><div><span>Depends on</span><b>${t.deps.length?t.deps.join(' · '):t.removed?'Removed from inception':'Confirmed client context'}</b></div><div><span>Type</span><b>${t.removed?'Removed task':t.laterTrack||t.later?'Later activation':t.human?'Human decision':'Validation task'}</b></div></div>${sourceBlock(refs,src)}`:`<div class="rr-detail-head"><div><span class="rr-detail-label">EVIDENCE TO DECISION</span><h3>${safe(r.name)} · ${scenarios[state.scene].label}</h3></div></div><div class="rr-chain"><div><span>1 · Evidence</span><p>${safe(r.facts[state.scene])}</p></div><i>→</i><div><span>2 · AI recommendation</span><p>${safe(r.action[state.scene])}</p></div><i>→</i><div><span>3 · Human decision</span><p>${safe(r.human)}</p></div></div>${sourceBlock(refs,src)}<p class="rr-note">${safe(r.note)}</p>`;}
    function drawEdges(){if(typeof canvas.getBoundingClientRect!=='function')return;const ts=tasks(),rect=canvas.getBoundingClientRect(),width=canvas.scrollWidth,height=canvas.scrollHeight;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('width',width);svg.setAttribute('height',height);const defs=`<defs><marker id="rr-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#bcc8d2"></path></marker><marker id="rr-arrow-active" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#0b7d78"></path></marker></defs>`,paths=[];ts.forEach(target=>{if(target.removed)return;target.deps.forEach(id=>{const fromTask=ts.find(t=>t.id===id&&!t.removed),from=fromTask&&root.querySelector('#rr-'+id),to=root.querySelector('#rr-'+target.id);if(!from||!to||typeof from.getBoundingClientRect!=='function'||typeof to.getBoundingClientRect!=='function')return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=a.right-rect.left,y1=a.top+a.height/2-rect.top,x2=b.left-rect.left,y2=b.top+b.height/2-rect.top,bend=Math.max(34,(x2-x1)*.44),active=related(fromTask)&&related(target);paths.push(`<path class="rr-edge ${active?'active':''}" d="M ${x1} ${y1} C ${x1+bend} ${y1}, ${x2-bend} ${y2}, ${x2} ${y2}" marker-end="url(#rr-arrow${active?'-active':''})"></path>`);});});svg.innerHTML=defs+paths.join('');}
    function render(){renderScenarios();renderRisks();renderGraph();}
    root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!root.contains(b))return;if(b.dataset.scene!==undefined){state.scene=Number(b.dataset.scene);state.task=null;state.source=null;render();if(options.onSelect)options.onSelect(state.risk,scenarios[state.scene].id);}else if(b.dataset.risk){state.risk=b.dataset.risk;state.task=null;state.source=null;render();if(options.onSelect)options.onSelect(state.risk,scenarios[state.scene].id);}else if(b.dataset.task){state.task=state.task===b.dataset.task?null:b.dataset.task;state.source=null;renderGraph();}else if(b.hasAttribute('data-clear-task')){state.task=null;state.source=null;renderGraph();}else if(b.dataset.mapSource){state.source=b.dataset.mapSource;renderEvidence();}});
    const observer=new ResizeObserver(()=>requestAnimationFrame(drawEdges));observer.observe(canvas);render();return()=>observer.disconnect();
  }
};
