window.SA_RISK_MAP = {
  markup: `
    <div id="sa-route-risk">
      <header class="rr-heading">
        <div>
          <div class="rr-eyebrow">ALPENRIDGE · DECISION PATH</div>
          <h2>See how new evidence changes risk and workflow</h2>
          <p class="rr-intro">Review what the agents inferred from dated evidence, or build a what-if scenario. The graph recalculates the tasks, dependencies and human decisions affected by each requirement.</p>
        </div>
        <div class="rr-mandate"><b>$250m</b><span>Global IG bond mandate<br>Swiss pension foundation</span></div>
      </header>
      <section aria-labelledby="rr-snapshot-heading">
        <div class="rr-section-title"><div><span class="rr-step-number">1</span><div><h3 id="rr-snapshot-heading">Set the client requirements</h3><p>Use source-backed updates or adjust five requirement areas to test a different route.</p></div></div><span class="rr-help">Controls change the workflow immediately</span></div>
        <div class="rr-mode-switch" role="group" aria-label="Scenario source"><button type="button" data-map-mode="timeline">Evidence timeline</button><button type="button" data-map-mode="builder">Build a what-if</button></div>
        <div id="rr-timeline"><div class="rr-scenarios" id="rr-scenarios"></div><div class="rr-scenario-note"><b>These are evidence updates, not the only scenarios.</b> The what-if builder can model other combinations while keeping the human approval gates visible.</div></div>
        <div id="rr-builder" hidden></div>
      </section>
      <section class="rr-risk-section" aria-labelledby="rr-risk-heading">
        <div class="rr-section-title"><div><span class="rr-step-number">2</span><div><h3 id="rr-risk-heading">Choose a requirement to trace</h3><p>Low, Medium and High describe operational attention—not investment risk or probability of loss.</p></div></div></div>
        <div class="rr-risk-picker" id="rr-risk-picker"></div>
      </section>
      <section class="rr-graph-section" aria-labelledby="rr-graph-title">
        <div class="rr-graph-head">
          <div><span class="rr-step-number">3</span><div><h3 id="rr-graph-title">Dependency graph</h3><p id="rr-graph-subtitle"></p></div></div>
          <div class="rr-legend"><span><i class="rr-legend-line active"></i>Selected risk path</span><span><i class="rr-legend-line"></i>Other dependency</span><span><i class="rr-legend-diamond"></i>Human decision</span></div>
        </div>
        <div class="rr-risk-summary" id="rr-risk-summary"></div>
        <div class="rr-graph-scroll" tabindex="0" aria-label="Scrollable onboarding dependency graph"><div class="rr-graph-canvas" id="rr-graph-canvas"><svg class="rr-edges" id="rr-edges" aria-hidden="true"></svg><div class="rr-columns" id="rr-columns" role="group" aria-label="Onboarding tasks across five phases"></div></div></div>
      </section>
      <section class="rr-evidence" id="rr-evidence" aria-live="polite"></section>
      <footer class="rr-foot"><span>Evidence linked</span><span>Human approval retained</span><span>Plan revises when client facts change</span></footer>
    </div>`,
  mount(options = {}) {
    const root = document.getElementById('sa-route-risk');
    const scenariosRoot = root.querySelector('#rr-scenarios');
    const timelineRoot = root.querySelector('#rr-timeline');
    const builderRoot = root.querySelector('#rr-builder');
    const riskPicker = root.querySelector('#rr-risk-picker');
    const columns = root.querySelector('#rr-columns');
    const canvas = root.querySelector('#rr-graph-canvas');
    const svg = root.querySelector('#rr-edges');
    const evidence = root.querySelector('#rr-evidence');
    const source = Object.fromEntries(window.CORPUS.documents.flatMap(d => d.chunks.map(c => [c.id, [d.title + ' · v' + d.version, c.text]])));
    const scenarios = [
      {id:'initial',date:'Mon · 14 Sep',label:'Initial request',change:'Starting position',funding:'$200m securities + $50m cash',reporting:'Monday weekly CHF analytics requested',derivatives:'Derivatives requested at launch',delta:'Mixed funding creates transfer dependencies.'},
      {id:'clarified',date:'Tue · 15 Sep',label:'Reporting clarified',change:'Reporting changed only',funding:'$200m securities + $50m cash',reporting:'Tuesday holdings + monthly analytics accepted',derivatives:'Derivatives still requested at launch',delta:'Reporting falls from High to Lower. Funding is unchanged.'},
      {id:'cash',date:'Wed · 16 Sep',label:'Cash + later derivatives',change:'Funding and launch scope changed',funding:'$250m cash · no securities transferred',reporting:'Clarified reporting remains in force',derivatives:'Derivatives move to a later approval',delta:'Transfer turns Off. Derivatives become a separate later path.'}
    ];
    const risks = {
      reporting:{name:'Reporting',statuses:['High','Lower','Lower'],levels:['high','lower','lower'],route:['T02','T05','T06','T10','T12','T13'],ai:'Compare the requested service with current operating capability and relevant precedents.',facts:['Monday weekly analytics exceed the current supported service.','The client accepts Tuesday holdings and monthly analytics.','The clarified reporting scope remains in force.'],action:['Negotiate the service during intake and test a sample before commitment.','Update the annex and validate the account-specific custody feed.','Keep annex alignment, feed testing and first-cycle validation.'],human:'Client Reporting validates feasibility; Legal and the client approve the service terms.',refs:[['N01§2','O01§1','H05-S§1'],['N07§1','N06§2','H05-S§1'],['N07§1','N06§2','H05-S§1']],note:'Historical rework makes this an early attention area. The cohort is descriptive evidence, not a calibrated forecast.'},
      restrictions:{name:'Restrictions',statuses:['High','High','High'],levels:['high','high','high'],route:['T03','T05','T07','T11','T10','T12'],ai:'Compare contractual clauses and turn ambiguity into testable interpretation questions.',facts:['IMA uses >5%; policy uses ≥5%; thermal coal is undefined.','The reporting clarification does not change the restriction ambiguity.','Cash funding removes transfer screening, but purchase restrictions still apply.'],action:['Resolve intent before coding or definitive transfer screening.','Keep the Legal and FI PC interpretation workshop.','Approve and test the rules before the portfolio buys securities.'],human:'The client and Legal decide intent; FI PC validates implementation and boundary tests.',refs:[['N02§1','N03§1','H02-G§1','H08-G§3'],['N02§1','N03§1','H08-G§3'],['N03§1','N08§2','H08-G§3']],note:'At exactly 5%, the two tobacco operators produce different results. Cash funding does not remove that issue.'},
      transfer:{name:'Funding route',statuses:['High','High','Low'],levels:['high','high','low'],route:['T03','T07','T11','T08','T10','T12'],ai:'Classify the proposed funding route, then connect its facts to transfer, cash confirmation and launch dependencies.',facts:['Mixed funding includes three $10m securities with threshold, coal-scope or missing-data questions.','The reporting clarification does not change the proposed securities transfer.','The route is $250m cash; no legacy securities enter the account at inception.'],action:['Interpret, screen and obtain an explicit disposition decision.','Retain the transfer screen and client/PM disposition review.','Remove in-kind screening; confirm cash instructions, launch scope and portfolio construction.'],human:'Client and PM choose the funding route; Transition validates final securities or cash instructions.',refs:[['N04§2','N04§3'],['N04§2','N04§3'],['N08§1','N08§2']],note:'Cash is a classified funding fact, not a risk by itself. All cash removes legacy-security screening but still requires instruction, launch and investment controls.'},
      derivatives:{name:'Derivatives',statuses:['Watch','Watch','Later'],levels:['watch','watch','later'],route:['T09','T10','T12','T14'],ai:'Compare full-scope and staged routes with the available readiness evidence.',facts:['Day-one derivatives are requested; readiness dates are missing.','The reporting change does not establish derivative readiness.','The client proposes later activation after the cash-bond launch.'],action:['Obtain readiness dates and assess the launch-scope options.','Keep readiness discovery and the PM/client scope decision.','Run a separate readiness path and later activation decision.'],human:'PM and client accept the investment implications; Legal and Operations confirm readiness.',refs:[['O04§2','H03-T§2'],['O04§2','H03-T§2'],['N08§2','O04§2']],note:'Later is a sequencing decision, not approval. A proposed day 30 remains subject to readiness.'},
      legal:{name:'Legal applicability',statuses:['Gap','Gap','Gap'],levels:['gap','gap','gap'],route:['T04','T05','T10'],ai:'Detect that authoritative evidence is missing and route the question to the qualified owner.',facts:['Swiss domicile is known; applicable requirements are not established.','Reporting clarification does not close the legal evidence gap.','The funding change does not close the legal evidence gap.'],action:['Request the Legal applicability determination.','Retain the authoritative requirements review.','Retain the authoritative requirements review.'],human:'Legal determines applicable requirements using current authoritative sources.',refs:[['O05§1','O05§2'],['O05§1','O05§2'],['O05§1','O05§2']],note:'The system does not infer Swiss legal or tax requirements from domicile alone.'}
    };
    const levels=['Low','Medium','High'];
    const builderDefinitions={
      reporting:{name:'Reporting',conditions:['Standard supported cadence is confirmed.','Enhanced cadence needs a feed sample and SLA validation.','Requested Monday analytics conflict with the supported service.'],facts:['Tuesday holdings and monthly analytics use a supported service.','The service is plausible, but a sample feed or operating detail remains open.','Monday weekly analytics exceed the currently supported service.'],actions:['Record the agreed annex and validate the first live cycle.','Test a sample and confirm the SLA before final commitment.','Negotiate the service and validate feasibility before contract approval.'],impact:[[0,1],[1,3],[3,7]],rework:['0 days in preventive comparator','2–5 days planning estimate','7–12 days observed'],cases:['H05','H01 · H04 · H06 · H10','H01 · H04 · H06 · H10'],refs:[['N07§1','H05-S§1'],['N06§2','O01§1'],['N01§2','O01§1','H01-I§2']]},
      restrictions:{name:'Restrictions',conditions:['Wording is approved and testable.','One interpretation or data question remains open.','Thresholds conflict or a restricted activity is undefined.'],facts:['Legal and the client have approved testable restriction wording.','One restriction boundary or issuer-data question still needs validation.','The IMA uses >5%, policy uses ≥5%, and thermal coal is undefined.'],actions:['Code the approved rules and retain boundary-test evidence.','Run an interpretation workshop and test the remaining boundary.','Resolve client intent before coding or buying securities.'],impact:[[0,1],[1,3],[3,6]],rework:['0 days in clear-language cases','2–4 days planning estimate','4–8 days observed'],cases:['H07 · H10','H03','H02 · H04 · H08'],refs:[['H08-G§3'],['N03§1','H02-G§1'],['N02§1','N03§1','H08-G§3']]},
      transfer:{name:'Funding route',conditions:['$250m all cash; no legacy securities transfer.','$200m securities + $50m cash; eligibility is pending.','In-kind-heavy route includes flagged or incomplete positions.'],facts:['The account is funded with $250m cash; legacy holdings remain outside.','Mixed funding requires both cash confirmation and securities eligibility screening.','The proposed transfer contains flagged positions or missing data that can block disposition.'],actions:['Remove in-kind screening; confirm cash instructions and portfolio-construction readiness.','Screen securities, confirm cash and obtain a client/PM disposition decision.','Resolve data and restriction exceptions before authorizing the transfer.'],impact:[[0,1],[1,3],[2,6]],rework:['0 transfer days; cash controls remain','2–5 days planning estimate','4–8 days observed'],cases:['H05 · H11','H03 · H09','H04 · H06 · H08 · H10'],refs:[['N08§1','N08§2'],['N04§1','N04§3'],['N04§2','N04§3']]},
      derivatives:{name:'Derivatives',conditions:['Not required for launch.','Later activation is proposed; readiness work continues.','Day-one use is requested without confirmed readiness.'],facts:['Derivatives are outside the initial launch scope.','A later activation path is proposed, subject to readiness and approval.','Day-one derivatives are requested but readiness dates are missing.'],actions:['Remove derivatives from the inception critical path.','Prepare a separate readiness path and later human approval.','Obtain dates and resolve documentation, broker and operational readiness.'],impact:[[0,0],[0,2],[4,8]],rework:['0 days on initial critical path','6–12 days may continue after launch','6–12 days observed'],cases:['H07 · H11','H03 · H04 · H06','H03 · H04 · H06 · H08 · H10'],refs:[['N08§2'],['N08§2','O04§2'],['O04§2','H03-T§2']]},
      legal:{name:'Legal applicability',conditions:['Authoritative determination is completed.','Legal review is underway.','No authoritative applicability determination exists.'],facts:['Legal has recorded the applicable requirements and required documents.','The authoritative review is active, but the determination is not final.','Swiss domicile is known; applicable requirements are not established.'],actions:['Carry the determination into the annex and control record.','Keep the review as a visible dependency and avoid premature commitment.','Route the question to Legal; do not infer requirements from domicile.'],impact:[[0,1],[2,4],[4,8]],rework:['0–1 day closeout','2–4 day documentation proxy','4–8 day documentation proxy'],cases:['Completed-review cases','Comparable documentation cases','Comparable documentation cases'],refs:[['O05§2'],['O05§1','O05§2'],['O05§1','O05§2']]}
    };
    const baseTasks = [
      {id:'T02',phase:0,title:'Agree reporting scope',owner:'Client Reporting + RM',deps:[],human:true,refs:['N01§2','O01§1','H05-S§1']},
      {id:'T03',phase:0,title:'Clarify restriction intent',owner:'Legal + FI PC + client',deps:[],human:true,refs:['N02§1','N03§1','H02-G§1']},
      {id:'T04',phase:0,title:'Determine legal applicability',owner:'Legal',deps:[],human:true,refs:['O05§2']},
      {id:'T05',phase:1,title:'Accept mandate annexes',owner:'Legal + client',deps:['T02','T03','T04'],human:true,refs:['N03§1','N05§3']},
      {id:'T06',phase:2,title:'Validate sample feed',owner:'Reporting + Results + Custody',deps:['T02'],human:false,refs:['N06§2','O01§1']},
      {id:'T07',phase:2,title:'Test investment rules',owner:'FI PC + ESG',deps:['T03'],human:false,refs:['H02-G§1','H08-G§3']},
      {id:'T08',phase:2,title:'Confirm custody and systems',owner:'GCS Operations + Custody',deps:[],human:false,refs:['N05§3']},
      {id:'T09',phase:2,title:'Check derivative readiness',owner:'Operations + Legal + PM',deps:[],human:false,refs:['O04§2']},
      {id:'T11',phase:2,title:'Screen transfer and exceptions',owner:'Transition + FI PC + PM/client',deps:['T03','T07'],human:true,refs:['N04§2','N04§3']},
      {id:'T10',phase:3,title:'Agree launch scope',owner:'GCS Operations + PM + client',deps:['T05','T06','T07','T08','T09','T11'],human:true,refs:['O04§2','N05§3']},
      {id:'T12',phase:3,title:'Confirm funding mix',owner:'Transition + client',deps:['T10','T11'],human:true,refs:['N04§3']},
      {id:'T13',phase:4,title:'Validate first reporting cycle',owner:'Client Reporting + Operations',deps:['T12'],human:false,refs:['H05-S§1']},
      {id:'T14',phase:4,title:'Approve later activation',owner:'PM + Legal + Operations',deps:['T09','T12'],human:true,refs:['N08§2','O04§2'],later:true}
    ];
    const phases=[['01','Intake','Resolve client intent'],['02','Paperwork','Record approved terms'],['03','Operational setup','Configure and test'],['04','Funding','Authorize the route'],['05','Post-funding','Validate live operation']];
    const state={scene:Math.max(0,scenarios.findIndex(s=>s.id===options.scenario)),risk:options.risk||'reporting',task:null,source:null,mode:'timeline',custom:{reporting:2,restrictions:2,transfer:1,derivatives:1,legal:2}};
    const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const customStatus=id=>levels[state.custom[id]];
    const customLevel=id=>customStatus(id).toLowerCase();
    const timelineIndex={reporting:[2,0,0],restrictions:[2,2,2],transfer:[2,2,0],derivatives:[2,2,1],legal:[2,2,2]};
    const impactText=range=>range[0]===range[1]?`${range[0]} business day${range[0]===1?'':'s'}`:`${range[0]}–${range[1]} business days`;
    function aggregateImpact(){const ranges=Object.keys(builderDefinitions).map(id=>builderDefinitions[id].impact[state.custom[id]]),highs=Object.values(state.custom).filter(v=>v===2).length,minimum=Math.max(...ranges.map(r=>r[0])),maximum=Math.max(...ranges.map(r=>r[1]))+Math.min(3,Math.max(0,highs-1));return [minimum,maximum];}
    function current(){
      const r=risks[state.risk];
      const d=builderDefinitions[state.risk];
      if(state.mode==='builder'){const i=state.custom[state.risk];return {label:'Your what-if',date:'Custom route',funding:builderDefinitions.transfer.conditions[state.custom.transfer],status:customStatus(state.risk),level:customLevel(state.risk),fact:d.facts[i],action:d.actions[i],impact:d.impact[i],rework:d.rework[i],cases:d.cases[i],refs:d.refs[i]};}
      const s=scenarios[state.scene],i=timelineIndex[state.risk][state.scene];return {label:s.label,date:s.date,funding:s.funding,status:r.statuses[state.scene],level:r.levels[state.scene],fact:r.facts[state.scene],action:r.action[state.scene],impact:d.impact[i],rework:d.rework[i],cases:d.cases[i],refs:r.refs[state.scene]};
    }
    function tasks(){
      const scenario=state.mode==='builder'?(state.custom.transfer===0?'cash':'initial'):scenarios[state.scene].id;
      const showLater=scenario==='cash'||(state.mode==='builder'&&state.custom.derivatives===1);
      return baseTasks.filter(t=>!t.later||showLater).map(t=>{
        const plan=window.AGENT_DEMO.workflow(scenario).find(p=>p.id===t.id);const edit=options.taskEdits?.[t.id]||{};
        const x={...t,deps:plan?[...plan.depends]:[...t.deps],refs:plan?[...plan.evidence]:[...t.refs],owner:edit.owner||plan?.owner||t.owner,timing:edit.timing||plan?.timing||''};
        if(state.mode==='timeline'&&x.id==='T02'&&state.scene>0){x.title='Align clarified reporting';x.refs=['N07§1','N06§2'];}
        if(scenario==='cash'){if(x.id==='T11'){x.removed=true;x.title='In-kind screen removed';x.deps=[];x.refs=['N08§1','N08§2'];}if(x.id==='T10')x.deps=x.deps.filter(d=>d!=='T11');if(x.id==='T12'){x.title='Confirm $250m cash';x.deps=['T10'];x.refs=['N08§1'];}}
        if(state.mode==='builder'){
          if(x.id==='T02')x.title=['Record supported reporting','Validate enhanced reporting','Resolve reporting conflict'][state.custom.reporting];
          if(x.id==='T03')x.title=['Record approved restrictions','Clarify restriction detail','Resolve conflicting restrictions'][state.custom.restrictions];
          if(x.id==='T04')x.title=['Record Legal determination','Complete Legal review','Determine legal applicability'][state.custom.legal];
          if(x.id==='T11'&&state.custom.transfer===2)x.title='Resolve flagged transfer exceptions';
          if(x.id==='T09'){
            if(state.custom.derivatives===0){x.removed=true;x.title='Derivatives outside launch';x.deps=[];}
            if(state.custom.derivatives===1){x.title='Prepare later derivatives';x.laterTrack=true;}
            if(state.custom.derivatives===2)x.title='Resolve day-one derivative readiness';
          }
          if(x.id==='T10'){
            if(state.custom.derivatives<2)x.deps=x.deps.filter(d=>d!=='T09');
            if(state.custom.transfer===0)x.deps=x.deps.filter(d=>d!=='T11');
          }
          if(x.id==='T14'&&state.custom.derivatives===1)x.title='Approve later derivative activation';
        }
        return x;
      });
    }
    function related(t){
      if((state.mode==='timeline'&&state.scene===2||state.mode==='builder'&&state.custom.transfer===0)&&state.risk==='transfer')return['T11','T10','T12'].includes(t.id);
      if(state.risk==='derivatives'&&((state.mode==='timeline'&&state.scene===2)||state.mode==='builder'&&state.custom.derivatives===1))return['T09','T12','T14'].includes(t.id);
      return risks[state.risk].route.includes(t.id);
    }
    function renderScenarios(){scenariosRoot.innerHTML=scenarios.map((s,i)=>`<button type="button" class="rr-scenario-card ${i===state.scene?'selected':''}" data-scene="${i}" aria-pressed="${i===state.scene}"><span class="rr-scenario-top"><span class="rr-date">${s.date}</span><span class="rr-scenario-kicker">${safe(s.change)}</span></span><strong>${safe(s.label)}</strong><dl><div><dt>Funding</dt><dd>${safe(s.funding)}</dd></div><div><dt>Reporting</dt><dd>${safe(s.reporting)}</dd></div><div><dt>Derivatives</dt><dd>${safe(s.derivatives)}</dd></div></dl><span class="rr-change">${safe(s.delta)}</span></button>`).join('');}
    function renderBuilder(){const total=aggregateImpact();builderRoot.innerHTML=`<div class="rr-delay-overview"><div><span>Estimated critical-path impact</span><strong>+${impactText(total)}</strong><small>Calculated from the five selected conditions</small></div><p><b>Do not add the five estimates.</b> Onboarding workstreams run in parallel. The range reflects the longest likely dependency plus a small interaction allowance when several High conditions converge. H04 recorded multiple rework streams but only a five-business-day launch movement.</p></div><div class="rr-severity-guide"><div><b>Low</b><span>Supported or approved; routine controls remain.</span></div><div><b>Medium</b><span>A validation or decision is open; work can usually proceed in parallel.</span></div><div><b>High</b><span>A conflict, evidence gap or readiness issue can block downstream work.</span></div></div><div class="rr-builder-grid">${Object.entries(builderDefinitions).map(([id,d])=>{const i=state.custom[id];return `<label class="rr-control ${id===state.risk?'selected':''}"><span class="rr-control-head"><b>${safe(d.name)}</b><em data-level="${customLevel(id)}">${customStatus(id)}</em></span><input type="range" min="0" max="2" step="1" value="${i}" data-custom="${id}" aria-label="${safe(d.name)} attention level"><span class="rr-scale"><i>Low</i><i>Medium</i><i>High</i></span><strong>${safe(d.conditions[i])}</strong><span class="rr-control-impact"><b>Potential launch impact</b><strong>+${impactText(d.impact[i])}</strong><small>${safe(d.rework[i])} · ${safe(d.cases[i])}</small></span></label>`;}).join('')}</div><p class="rr-builder-note"><b>Funding route clarification:</b> all cash is not labelled a safe investment. It is Low operational attention for legacy transfer because no securities move in-kind; cash instructions, portfolio construction and purchase restrictions still remain in the plan.</p>`;}
    function renderMode(){timelineRoot.hidden=state.mode!=='timeline';builderRoot.hidden=state.mode!=='builder';root.querySelectorAll('[data-map-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mapMode===state.mode);b.setAttribute('aria-pressed',b.dataset.mapMode===state.mode);});if(state.mode==='builder')renderBuilder();}
    function renderRisks(){riskPicker.innerHTML=Object.entries(risks).map(([id,r])=>{const status=state.mode==='builder'?customStatus(id):r.statuses[state.scene],level=state.mode==='builder'?customLevel(id):r.levels[state.scene];return `<button type="button" class="rr-risk-button ${id===state.risk?'selected':''}" data-risk="${id}" aria-pressed="${id===state.risk}"><span>${safe(r.name)}</span><b data-level="${level}">${status}</b></button>`;}).join('');}
    function renderGraph(){const c=current(),r=risks[state.risk],ts=tasks();root.querySelector('#rr-graph-title').textContent=`${r.name} dependency path · ${c.date}`;root.querySelector('#rr-graph-subtitle').textContent=`${c.label}: ${c.funding}`;root.querySelector('#rr-risk-summary').innerHTML=`<div class="rr-summary-status" data-level="${c.level}"><span>${safe(r.name)}</span><b>${c.status}</b></div><div><span class="rr-summary-label">Why this status</span><p>${safe(c.fact)}</p></div><div><span class="rr-summary-label">What the plan does</span><p>${safe(c.action)}</p></div><div class="rr-summary-impact"><span class="rr-summary-label">Estimated launch impact</span><strong>+${impactText(c.impact)}</strong><p>${safe(c.rework)} · basis: ${safe(c.cases)}</p></div>`;columns.innerHTML=phases.map((p,phase)=>`<section class="rr-phase ${ts.some(t=>t.phase===phase&&related(t)&&!t.removed)?'active':''}"><header><span>${p[0]}</span><div><h4>${p[1]}</h4><p>${p[2]}</p></div></header><div class="rr-nodes">${ts.filter(t=>t.phase===phase).map(t=>`<article class="rr-node ${related(t)?'relevant':'dimmed'} ${t.removed?'removed':''} ${t.laterTrack||t.later?'later':''}" id="rr-${t.id}"><button type="button" data-task="${t.id}" aria-pressed="${state.task===t.id}"><span class="rr-node-top"><b>${t.id}</b><em>${t.removed?'Removed':t.laterTrack||t.later?'Later track':t.human?'Human decision':'Validation'}</em></span><strong>${safe(t.title)}</strong><span class="rr-owner">${safe(t.owner)}</span><span class="rr-dep-count">${t.deps.length?`${t.deps.length} dependenc${t.deps.length===1?'y':'ies'}`:t.removed?'Not in inception route':'Starts from client context'}</span></button></article>`).join('')}</div></section>`).join('');renderEvidence();requestAnimationFrame(drawEdges);}
    function sourceBlock(refs,src){return `<div class="rr-sources">${refs.map(id=>`<button type="button" class="btn btn-ghost" data-map-source="${id}" aria-pressed="${state.source===id}">${id}</button>`).join('')}</div><blockquote class="rr-quote"><span>${safe(src[0])} · ${safe(state.source)}</span><p>${safe(src[1])}</p></blockquote><button type="button" class="btn small" data-source="${safe(state.source)}">Open full source document</button>`;}
    function renderEvidence(){const r=risks[state.risk],c=current(),t=tasks().find(x=>x.id===state.task),refs=t?t.refs:c.refs;if(!refs.includes(state.source))state.source=refs[0];const src=source[state.source]||['Source record','Source passage unavailable in this snapshot.'];evidence.innerHTML=t?`<div class="rr-detail-head"><div><span class="rr-detail-label">SELECTED TASK</span><h3>${safe(t.id+' · '+t.title)}</h3></div><button type="button" class="btn small" data-clear-task>Back to requirement explanation</button></div><div class="rr-task-detail"><div><span>Owner</span><b>${safe(t.owner)}</b></div><div><span>Depends on</span><b>${t.deps.length?t.deps.join(' · '):t.removed?'Removed from inception':'Confirmed client context'}</b></div><div><span>Type</span><b>${t.removed?'Removed task':t.laterTrack||t.later?'Later activation':t.human?'Human decision':'Validation task'}</b></div></div>${sourceBlock(refs,src)}`:`<div class="rr-detail-head"><div><span class="rr-detail-label">EVIDENCE TO DECISION</span><h3>${safe(r.name)} · ${safe(c.label)}</h3></div></div><div class="rr-chain"><div><span>1 · Classified fact</span><p>${safe(c.fact)}</p></div><i>→</i><div><span>2 · Agent recommendation</span><p>${safe(c.action)}</p></div><i>→</i><div><span>3 · Human decision</span><p>${safe(r.human)}</p></div></div>${sourceBlock(refs,src)}<p class="rr-note">${state.mode==='builder'?'This what-if uses selected assumptions and the cited evidence pattern; a reviewer must validate it before use. ':''}${safe(r.note)}</p>`;}
    function drawEdges(){if(typeof canvas.getBoundingClientRect!=='function')return;const ts=tasks(),rect=canvas.getBoundingClientRect(),width=canvas.scrollWidth,height=canvas.scrollHeight;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('width',width);svg.setAttribute('height',height);const defs=`<defs><marker id="rr-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#bcc8d2"></path></marker><marker id="rr-arrow-active" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#0b7d78"></path></marker></defs>`,paths=[];ts.forEach(target=>{if(target.removed)return;target.deps.forEach(id=>{const fromTask=ts.find(t=>t.id===id&&!t.removed),from=fromTask&&root.querySelector('#rr-'+id),to=root.querySelector('#rr-'+target.id);if(!from||!to||typeof from.getBoundingClientRect!=='function'||typeof to.getBoundingClientRect!=='function')return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=a.right-rect.left,y1=a.top+a.height/2-rect.top,x2=b.left-rect.left,y2=b.top+b.height/2-rect.top,bend=Math.max(34,(x2-x1)*.44),active=related(fromTask)&&related(target);paths.push(`<path class="rr-edge ${active?'active':''}" d="M ${x1} ${y1} C ${x1+bend} ${y1}, ${x2-bend} ${y2}, ${x2} ${y2}" marker-end="url(#rr-arrow${active?'-active':''})"></path>`);});});svg.innerHTML=defs+paths.join('');}
    function render(){renderScenarios();renderMode();renderRisks();renderGraph();}
    function onClick(e){const b=e.target.closest('button');if(!b||!root.contains(b))return;if(b.dataset.mapMode){state.mode=b.dataset.mapMode;state.task=null;state.source=null;render();}else if(b.dataset.scene!==undefined){state.mode='timeline';state.scene=Number(b.dataset.scene);state.task=null;state.source=null;render();if(options.onSelect)options.onSelect(state.risk,scenarios[state.scene].id);}else if(b.dataset.risk){state.risk=b.dataset.risk;state.task=null;state.source=null;render();if(options.onSelect)options.onSelect(state.risk,state.mode==='builder'?'custom':scenarios[state.scene].id);}else if(b.dataset.task){state.task=state.task===b.dataset.task?null:b.dataset.task;state.source=null;renderGraph();}else if(b.hasAttribute('data-clear-task')){state.task=null;state.source=null;renderGraph();}else if(b.dataset.mapSource){state.source=b.dataset.mapSource;renderEvidence();}}
    function onInput(e){const id=e.target?.dataset?.custom;if(!id||!(id in state.custom))return;state.mode='builder';state.custom[id]=Number(e.target.value);state.risk=id;state.task=null;state.source=null;renderBuilder();renderRisks();renderGraph();}
    root.addEventListener('click',onClick);root.addEventListener('input',onInput);
    const observer=new ResizeObserver(()=>requestAnimationFrame(drawEdges));observer.observe(canvas);render();return()=>{observer.disconnect();root.removeEventListener('click',onClick);root.removeEventListener('input',onInput);};
  }
};
