/* Two pages. portfolio = every onboarding in flight. output = what the agents produced for Alpenridge,
   as a one-screen board of six cards; each card opens its full detail in a side panel. */
(function(){
const O=window.SA_ONBOARD;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cites=refs=>refs&&refs.length?`<span class="cites inline">${refs.map(id=>`<button type="button" class="cite" data-source="${esc(id)}">${esc(id)}</button>`).join('')}</span>`:'';
const RAG={green:['On track','●'],amber:['At risk','▲'],red:['Off track','■'],grey:['Not started','○']};
const ragChip=(r,label)=>`<span class="st-rag st-${r}"><i aria-hidden="true">${RAG[r][1]}</i>${esc(label||RAG[r][0])}</span>`;
const plural=(n,w)=>`${n} ${w}${n===1?'':'s'}`;
const VEH={sa:'Separate account',cit:'CIT',mf:'Mutual fund'},REL=Object.fromEntries(O.ATTRS[1].options);
const STATUS={done:['Done','done'],progress:['In progress','progress'],late:['Running late','late'],overdue:['Overdue','overdue'],blocked:['Blocked','blocked'],waiting:['Waiting','waiting'],ready:['Not started','ready']};
function statusChip(r,s){const [label,cl]=STATUS[r.status];let extra='';
 if(r.status==='overdue')extra=` ${r.overdue}d`;
 if(r.status==='blocked')extra=` by ${r.openDeps.filter(d=>['overdue','late'].includes(s.map[d].status)).join(', ')}`;
 if(r.status==='waiting')extra=` on ${r.openDeps.slice(0,2).join(', ')}${r.openDeps.length>2?` +${r.openDeps.length-2}`:''}`;
 return `<span class="st-status st-s-${cl}">${label}${esc(extra)}</span>`;}
const OBLIGATIONS={
 contractual:[
  ['Tobacco exclusion: 5% or more of revenue (policy wording)','Awaiting client confirmation (P1)','amber',['N02§1','N03§1']],
  ['No thermal coal; activity and threshold to be defined','Awaiting client confirmation (P1)','amber',['N02§2']],
  ['5% single corporate-issuer limit; sovereigns exempt','Drafted in Schedule A','green',['N03§2']],
  ['FX forwards and rate futures, activated only after the day-30 review','Amendment in drafting (P5)','green',['N08§1','O04§2']],
  ['Weekly CHF holdings, Tuesday 12:00 Zurich','Service annex amended (P3)','green',['N07§1']],
  ['Monthly performance, attribution and ESG analytics, 5th business day','Service annex amended (P3)','green',['N07§1']],
  ['Negotiated fee schedule','In negotiation (P4)','green',[]]],
 non:[
  ['Material ready for the Monday trustee discussion','Met by Tuesday holdings + monthly pack; RM confirms','green',['N01§2']],
  ['Representative reporting sample before the client accepts the service','Sample reconciled 7 Oct (O2)','green',['N07§2']],
  ['Investment consultant copied on reports and reviews','Confirmed in the servicing model (I7)','green',['N01§2']],
  ['Visibility of watch areas and the route to readiness','Shared weekly by the RM','green',['N01§3']],
  ['Quarterly review meeting with trustees and consultant','Proposed by the RM; not in the contract','grey',[]],
  ['Named day-to-day servicing contact','Maya Shah, Client RM','green',['N01§1']]]
};
// What the client asked for, and where each ask stands now.
const REQUIREMENTS=[
 ['Reporting','Weekly CHF performance, attribution and ESG analytics by Monday 08:00 Zurich',['N01§2'],'Weekly CHF holdings Tuesday 12:00; monthly analytics on the 5th business day. Service annex amended.',['N07§1'],'green','Agreed 15 Sep'],
 ['Tobacco exclusion','Policy: 5% or more of revenue. Draft IMA: more than 5%.',['N03§1','N02§1'],'Interpretation workshop held 23 Sep. Waiting for the client to confirm the threshold in writing (P1).',['N02§1'],'amber','2 days overdue'],
 ['Thermal coal','“No thermal coal”, with no activity or threshold defined',['N02§2'],'Definition options agreed at the workshop. Waiting for the client to confirm in writing (P1).',['N02§2'],'amber','2 days overdue'],
 ['Issuer limit','5% single corporate issuer; sovereigns exempt',['N03§2'],'Drafted in Schedule A.',[],'green','Drafted'],
 ['Funding','USD 200m existing bonds in kind plus USD 50m cash',['N01§1'],'USD 250m cash at inception; legacy bonds stay with the outgoing manager.',['N08§1'],'green','Changed 16 Sep'],
 ['Derivatives','FX forwards and interest-rate futures from day one',['N01§3'],'Bond-only start; derivatives reviewed at day 30. Staged amendment in drafting (P5).',['N08§1'],'green','Changed 16 Sep'],
 ['Legal applicability','Swiss-domiciled client; applicable requirements unknown',['O05§1'],'Legal determination recorded 30 Sep.',['O05§2'],'green','Recorded'],
 ['Servicing','The consultant mentions another Swiss client’s weekly reporting',['N01§2'],'RM services the account directly; the consultant is copied on reports and reviews.',['N01§2'],'green','Confirmed']
];
const markup='<div id="st-root" class="st"></div>';
function mount(root,opt={}){
 const sent=()=>opt.sent?.()||[];
 const state={page:opt.page==='output'?'output':'portfolio',open:opt.open||null,lastOpen:null,stage:null,task:'P1',simTask:'P6',simDays:0};
 const sched=()=>O.schedule(O.TASKS,{extra:state.simDays?{[state.simTask]:state.simDays}:{}});
 const base=O.schedule();
 state.stage=base.stages.find(x=>!x.complete&&x.rag!=='grey')?.index??1;
 const team=id=>O.TEAMS[id]||id;
 /* ---------- Operator view ---------- */
 function summary(s){const open=s.rows.filter(r=>!r.done&&r.stage<4),over=open.filter(r=>r.status==='overdue'),blocked=open.filter(r=>r.status==='blocked'),gates=open.filter(r=>r.gate);
  return `<div class="st-account"><div><div class="eyebrow">Status as of ${O.fmt(O.AS_OF)} 2026</div><h2>Alpenridge Pension Foundation</h2><p class="st-tags"><span>Separate account</span><span>Consultant-advised</span><span>USD 250m global IG bonds</span><span>All-cash funding</span><span>Lead: GCS Operations</span></p></div>
  <div class="st-kpis"><div class="st-kpi"><span>Target funding</span><strong>${O.fmt(s.target)}</strong><small>Client date (N01)</small></div><div class="st-kpi ${s.slip>0?'bad':''}"><span>Forecast funding</span><strong>${O.fmt(s.funded)}</strong><small>${s.slip>0?`+${plural(s.slip,'business day')} late`:'On target'}</small></div><div class="st-kpi"><span>Open onboarding tasks</span><strong>${open.length}</strong><small>${over.length} overdue · ${blocked.length} blocked</small></div><div class="st-kpi"><span>Human decisions pending</span><strong>${gates.length}</strong><small>Before funding</small></div></div></div>`;}
 function stageStrip(s){return `<div class="st-stages" role="list">${s.stages.map(st=>`<button type="button" role="listitem" class="st-stage st-b-${st.rag} ${state.stage===st.index?'sel':''}" data-st-stage="${st.index}" aria-pressed="${state.stage===st.index}"><span class="st-stage-n">${String(st.index+1).padStart(2,'0')}</span><b>${st.short}</b>${ragChip(st.rag,st.complete?'Complete':RAG[st.rag][0])}<span class="st-stage-p">${st.progress} · ${st.done}/${st.tasks.length} done</span><small>${esc(st.why)}</small><span class="st-owner"><em>Owner</em>${esc(st.owner)} · ${esc(st.team)}</span><span class="st-owner"><em>Escalation</em>${esc(st.escalation)}</span></button>`).join('')}</div>`;}
 function issues(s){const roots=s.rows.filter(r=>!r.done&&r.own>0&&r.stage<4).map(r=>({r,imp:O.impact(r.id)})).sort((a,b)=>b.imp-a.imp||b.r.own-a.r.own);
  if(!roots.length)return `<section class="st-issues"><h3>Issues affecting the timeline</h3><p class="smalltext">Nothing is running late.</p></section>`;
  return `<section class="st-issues"><h3>Issues affecting the timeline <small>Root causes only; knock-on delays are in the drill-down</small></h3><div class="st-issue-list">${roots.map(({r,imp})=>`<button type="button" class="st-issue ${imp>0?'hit':''}" data-st-task="${r.id}"><span class="st-issue-title">${esc(r.issue||r.title)}</span><span class="st-impact">${imp>0?`+${plural(imp,'onboarding day')}`:'No date impact'}</span><small>${r.id} · ${esc(team(r.team))} · ${r.status==='overdue'?`${r.overdue}d overdue`:`+${r.own}d late`}${imp>0?` · funding ${O.fmt(s.funded-imp)} → ${O.fmt(s.funded)}`:' · absorbed by slack before funding'}</small>${r.reviews?`<span class="st-reviews">${r.reviews.map(x=>`<i>${esc(x)} required</i>`).join('')}</span>`:''}</button>`).join('')}</div></section>`;}
 function taskTable(s){const st=s.stages[state.stage];return `<div class="st-drill-head"><div><div class="eyebrow">Stage ${state.stage+1} drill-down</div><h3>${esc(st.name)} ${ragChip(st.rag,st.complete?'Complete':RAG[st.rag][0])}</h3></div><p class="smalltext">Owner <b>${esc(st.owner)}</b> · ${esc(st.team)} · escalates to ${esc(st.escalation)}${state.stage===4?' · not counted in onboarding duration':''}</p></div>
  <div class="tablewrap"><table class="st-table"><thead><tr><th>Task</th><th>Internal owner</th><th>External contact</th><th>Due</th><th>Forecast</th><th>Status</th></tr></thead><tbody>${st.tasks.map(r=>`<tr class="${state.task===r.id?'sel':''} ${r.status}" data-st-task="${r.id}" tabindex="0"><td><b>${r.id}</b> ${r.gate?'<i class="wr-gate-mark" title="Human decision">◇</i>':''}${esc(r.title)}</td><td>${esc(team(r.team))}</td><td>${esc(r.ext)}</td><td>${O.fmt(r.due)}</td><td class="${r.forecast>r.due&&!r.done?'late':''}">${r.done?`Done ${O.fmt(r.forecast,false)}`:O.fmt(r.forecast)}</td><td>${statusChip(r,s)}</td></tr>`).join('')}</tbody></table></div>`;}
 // Steps already taken come first, in order; the first one still to happen is Next.
 function escalationBlock(r,s,opt){const told=sent().includes('date')&&!opt?.extra,raw=O.escalation(r,s,opt).map(p=>told&&/^Client informed/.test(p.who)&&!p.hit?{...p,hit:true,when:'Sent from the agent run'}:p),path=[...raw.filter(p=>p.hit),...raw.filter(p=>!p.hit)];let next=path.findIndex(x=>!x.hit);if(!(r.overdue||r.slip>0))next=-2;
  return `<ol class="st-path">${path.map((p,i)=>`<li class="${p.hit?'hit':i===next?'next':''}"><b>${p.hit?'✓ Notified':i===next?'Next':'If needed'}</b><span>${esc(p.who)}</span><small>${esc(p.when)}</small></li>`).join('')}</ol>`;}
 function taskDetail(s){const r=s.map[state.task]||s.map.P1,down=s.reach(r.id),imp=r.done?0:O.impact(r.id);
  return `<aside class="st-detail"><div class="eyebrow">${r.id} · ${esc(O.STAGES[r.stage].name)}</div><h3>${esc(r.title)}</h3>${statusChip(r,s)} ${cites(r.refs)}
  <dl class="st-dl"><div><dt>Internal owner</dt><dd>${esc(team(r.team))}</dd></div><div><dt>External contact</dt><dd>${esc(r.ext)}</dd></div><div><dt>Due · forecast</dt><dd>${O.fmt(r.due)} · ${r.done?'done '+O.fmt(r.forecast):O.fmt(r.forecast)}</dd></div><div><dt>Waits on</dt><dd>${r.deps.length?r.deps.map(d=>`<button type="button" class="st-link" data-st-task="${d}">${d}</button>`).join(' '):'Nothing'}</dd></div><div><dt>Unblocks</dt><dd>${down.length?plural(down.length,'later task')+': '+down.slice(0,6).map(d=>`<button type="button" class="st-link" data-st-task="${d}">${d}</button>`).join(' ')+(down.length>6?' …':''):'Nothing downstream'}</dd></div><div><dt>Date impact</dt><dd>${r.done?'Complete':imp>0?`<b class="bad">+${plural(imp,'onboarding day')}</b>`:'None today'}</dd></div></dl>
  ${r.reviews?`<p class="st-reviews">${r.reviews.map(x=>`<i>${esc(x)} required</i>`).join('')}</p>`:''}
  <h4>Escalation and communication</h4>${r.done?'<p class="smalltext">Complete, no escalation.</p>':escalationBlock(r,s,{})}</aside>`;}
 function chain(s,b){const ids=['P6','O1','F2','F3','S1','S2'],labels={P6:'Contract signed',O1:'Funding setup',F2:'Cash instructions',F3:'Asset transfer · funded',S1:'Trading',S2:'Reporting'};
  return `<div class="st-chain">${ids.map((id,i)=>{const r=s.map[id],shift=r.forecast-b.map[id].forecast,late=r.forecast-r.due;return `${i?'<span class="st-chain-arrow" aria-hidden="true">→</span>':''}<button type="button" class="st-chain-node ${late>0?'late':''} ${shift>0?'moved':''}" data-st-sim="${id}"><em>${labels[id]}</em><b>${O.fmt(r.forecast)}</b><small>${late>0?`+${late}d vs plan ${O.fmt(r.due,false)}`:`Plan ${O.fmt(r.due,false)}`}</small>${shift>0?`<i>+${shift}d from this what-if</i>`:''}</button>`;}).join('')}</div>`;}
 function depsPane(s){const open=O.TASKS.filter(t=>t.done==null&&t.stage<4),b=base,moved=s.rows.filter(r=>r.forecast>b.map[r.id].forecast),stageChanges=s.stages.filter((x,i)=>x.rag!==b.stages[i].rag),sim=s.map[state.simTask];
  return `<section class="st-deps"><p class="smalltext">Each step waits on the one before, so an early delay moves everything after it unless there is slack. Pick a task and add a delay.</p>${chain(s,b)}
  <div class="st-sim"><label>What if this is delayed<select data-st-sim-task>${open.map(t=>`<option value="${t.id}" ${t.id===state.simTask?'selected':''}>${t.id} · ${esc(t.title)}</option>`).join('')}</select></label><div class="st-sim-days" role="radiogroup" aria-label="Extra business days">${[0,2,5,10].map(d=>`<button type="button" role="radio" aria-checked="${state.simDays===d}" class="${state.simDays===d?'active':''}" data-st-sim-days="${d}">${d?'+'+d+' days':'No delay'}</button>`).join('')}</div></div>
  ${state.simDays?`<div class="st-sim-out"><div><span class="eyebrow">Funding date</span><strong class="${s.funded>b.funded?'bad':''}">${O.fmt(b.funded)} → ${O.fmt(s.funded)}</strong><small>${s.funded>b.funded?`+${plural(s.funded-b.funded,'business day')}; ${s.slip} past the client target`:'Unchanged: the delay is absorbed by slack'}</small></div><div><span class="eyebrow">Tasks moved</span><strong>${moved.length}</strong><small>${moved.slice(0,8).map(r=>r.id).join(', ')}${moved.length>8?' …':''}</small></div><div><span class="eyebrow">Stages changing status</span><strong>${stageChanges.length}</strong><small>${stageChanges.map(x=>`${x.name}: ${RAG[b.stages[x.index].rag][0]} → ${RAG[x.rag][0]}`).join(' · ')||'None'}</small></div></div>
  <h4>Who gets notified if ${esc(sim.id)} slips ${state.simDays} days</h4>${escalationBlock({...sim,overdue:Math.max(sim.overdue,state.simDays),slip:Math.max(sim.slip,state.simDays)},s,{extra:{[state.simTask]:state.simDays}})}`:''}</section>`;}
 function players(s){const now=[],blocked=[],contact=[];
  const rows=O.PLAYERS.map(p=>{const ts=p.tasks.map(id=>s.map[id]),open=ts.filter(t=>!t.done),b=open.filter(t=>t.status==='blocked'),od=open.filter(t=>t.status==='overdue'),act=open.filter(t=>['progress','overdue','late','ready'].includes(t.status));
   let st;if(!open.length)st=['Done','done'];else if(od.length)st=['Overdue · must act now','overdue'];else if(b.length)st=['Blocked','blocked'];else if(act.length)st=['Acting now','progress'];else st=['Waiting','waiting'];
   const who=t=>t.ext&&t.ext!=='—'?t.ext:p.internal,add=(list,w,t)=>{if(!list.some(([,x])=>x.id===t.id))list.push([w,t]);};
   if(od.length){add(now,who(od[0]),od[0]);if(od[0].ext&&od[0].ext!=='—')add(contact,od[0].ext,od[0]);}
   else if(act.length)add(now,p.internal,act[0]);
   if(b.length)add(blocked,p.internal,b[0]);
   const next=open.sort((x,y)=>x.forecast-y.forecast)[0];
   return `<tr><td><b>${esc(p.area)}</b>${cites(p.refs)}</td><td>${esc(p.internal)}<small>${esc(team(p.team))}</small></td><td>${esc(p.ext)}</td><td>${esc(p.escalation)}</td><td><span class="st-status st-s-${st[1]}">${st[0]}</span>${next?`<small>Next: ${next.id} · ${esc(next.title)}</small>`:''}</td></tr>`;}).join('');
  return {rows,now,blocked,contact};}
 function whoActs(s){const {now,blocked,contact}=players(s),list=(xs,f)=>xs.length?xs.map(f).join(''):'<li>None</li>';
  return `<section class="st-next"><h3>Who acts next</h3><div class="st-who"><div><h4>Must act now</h4><ul>${list(now,([w,t])=>`<li><b>${esc(w)}</b> ${t.id} · ${esc(t.title)}</li>`)}</ul></div><div><h4>Blocked</h4><ul>${list(blocked,([w,t])=>`<li><b>${esc(w)}</b> ${t.id} waits on ${t.openDeps.join(', ')}</li>`)}</ul></div><div><h4>Must be contacted</h4><ul>${list(contact,([w,t])=>`<li><b>${esc(w)}</b> about ${t.id}, ${t.overdue}d overdue</li>`)}</ul></div></div></section>`;}
 function playersTable(s){const {rows}=players(s);
  return `<section class="panel"><div class="tablewrap"><table class="st-table"><thead><tr><th>Responsibility</th><th>Internal owner</th><th>External contact</th><th>Escalation point</th><th>Now</th></tr></thead><tbody>${rows}</tbody></table></div><p class="legend">Servicing after funding: Maya Shah (Client RM) services the account directly; the investment consultant is copied on reports and joins reviews. The client investment office is the instructing party.</p></section>`;}
 function obligationsPane(){const col=(title,sub,rows,how)=>`<section class="st-oblig"><h4>${title}</h4><p class="smalltext">${sub}</p><ul>${rows.map(([t,st,r,refs])=>`<li><span class="st-check st-c-${r}" aria-hidden="true">${r==='green'?'✓':r==='amber'?'!':'○'}</span><div><b>${esc(t)}</b><small>${esc(st)}</small>${cites(refs)}</div></li>`).join('')}</ul><p class="st-how"><b>How risk is judged:</b> ${how}</p></section>`;
  return `<section class="panel"><h3>Obligations</h3><p class="smalltext">Contractual and non-contractual obligations carry different risks, so they are tracked separately.</p><div class="st-oblig-grid">${col('Contractual obligations','Written into the IMA, Schedule A or the service annex. Binding once signed.',OBLIGATIONS.contractual,'a miss is a contract or guideline breach. FI Portfolio Control monitors with coded rules; any change needs Legal and a signed amendment.')}${col('Non-contractual expectations','Requested or promised in conversation. Not in the contract.',OBLIGATIONS.non,'a miss is a service or relationship risk. The Client RM owns these and can renegotiate without a contract amendment.')}</div></section>`;}
 // Actions sent from the end of the agent run show against the requirement they move forward.
 function requirementsTable(){const done=O.actions().filter(a=>sent().includes(a.id));return `<section class="panel"><h3>What the client asked for, and where it stands</h3>${done.length?`<p class="st-sent-note">✓ ${plural(done.length,'request')} sent today from the agent run. Each one shows against its requirement.</p>`:''}<div class="tablewrap"><table class="st-table st-req"><thead><tr><th>Requirement</th><th>Client asked</th><th>Where it stands now</th><th>Status</th></tr></thead><tbody>${REQUIREMENTS.map(([area,ask,askRefs,now,nowRefs,rag,label])=>{const a=done.filter(x=>x.req===area);return `<tr class="${a.length?'st-req-sent':''}"><td><b>${esc(area)}</b></td><td>${esc(ask)}${cites(askRefs)}</td><td>${esc(now)}${cites(nowRefs)}${a.map(x=>`<span class="st-sent">✓ Sent today: ${esc(x.action)} <em>to ${esc(x.to)}</em></span>`).join('')}</td><td>${ragChip(rag,label)}${a.length?'<span class="st-sent-chip">Request sent 8 Oct</span>':''}</td></tr>`;}).join('')}</tbody></table></div></section>`;}
 /* ---------- Agent output: one-screen board, detail in a side panel ---------- */
 const AGENT_IDS={'Context agent':'A1','Precedent agent':'A2','Operational risk agent':'A3','Investment risk agent':'A4','Playbook agent':'A5','Key players agent':'A6','Evidence reviewer':'A7'};
 const OUTS=[['req','Client requirements',['Context agent']],['oblig','Obligations',['Context agent','Evidence reviewer']],['risk','Risks & date impact',['Operational risk agent','Investment risk agent']],['plan','Plan & status',['Playbook agent']],['players','Key players',['Key players agent']],['whatif','What-if',['Playbook agent','Operational risk agent','Investment risk agent']]];
 const by=names=>`<span class="ob-by">${names.map(n=>`<span><i>${AGENT_IDS[n]}</i>${esc(n)}</span>`).join('')}</span>`;
 const line=(cls,text)=>`<li class="ob-${cls}">${text}</li>`;
 function summaryFor(id,s){
  const open=s.rows.filter(r=>!r.done&&r.stage<4),over=open.filter(r=>r.status==='overdue').length,blocked=open.filter(r=>r.status==='blocked').length;
  const roots=s.rows.filter(r=>!r.done&&r.own>0&&r.stage<4).map(r=>({r,imp:O.impact(r.id)})).sort((a,b)=>b.imp-a.imp);
  if(id==='req'){const settled=REQUIREMENTS.filter(r=>r[5]==='green').length,n=sent().length;return `<strong class="ob-big">${REQUIREMENTS.length}<small>requirements extracted · ${settled} settled · ${REQUIREMENTS.length-settled} waiting</small></strong><ul>${line('warn',n&&sent().includes('tobacco')?'Tobacco &amp; coal: 2 days overdue, confirmation requested today':'Tobacco &amp; coal: client confirmation 2 days overdue')}${n?line('ok',`${plural(n,'request')} sent to the client today`):line('ok','Reporting, funding and derivatives agreed or updated')}</ul>`;}
  if(id==='oblig'){const c=OBLIGATIONS.contractual,n=OBLIGATIONS.non;return `<strong class="ob-big">${c.length} + ${n.length}<small>contractual + non-contractual</small></strong><ul>${line('warn',`${c.filter(x=>x[2]==='amber').length} contractual terms waiting on the client`)}${line('info','Quarterly review is an expectation, not in the contract')}</ul>`;}
  if(id==='risk'){const top=roots[0],rest=roots.slice(1);return `<strong class="ob-big bad">+${top?top.imp:0} days<small>to onboarding from one open risk</small></strong><ul>${line('warn',`${esc(top.r.issue||top.r.title)}: needs Legal, Portfolio Control and the client`)}${rest[0]?line('ok',`${esc(rest[0].r.issue||rest[0].r.title)}: no date impact`):''}</ul>`;}
  if(id==='plan')return `<strong class="ob-big bad">${O.fmt(s.funded)}<small>forecast funding · client target ${O.fmt(s.target)}</small></strong><ul>${line('note',`${open.length} open tasks · ${over} overdue · ${blocked} blocked`)}${line('warn',`Contract signed ${O.fmt(s.map.P6.forecast,false)}, ${s.map.P6.forecast-s.map.P6.due} days after plan`)}</ul>`;
  if(id==='players'){const p=players(s);return `<strong class="ob-big">${O.PLAYERS.length}<small>responsibilities, each with owner, contact and escalation</small></strong><ul>${p.now[0]?line('warn',`Act now: ${esc(p.now[0][0].split(',')[0])} on ${p.now[0][1].id}`):''}${p.blocked[0]?line('warn',`Blocked: ${esc(p.blocked[0][0])}, waits on ${p.blocked[0][1].openDeps.join(', ')}`):''}</ul>`;}
  if(id==='whatif'){const d=O.schedule(O.TASKS,{extra:{P6:5}}),W=window.SA_WORKFLOW,cash=W?W.compute(W.PRESETS.find(p=>p.id==='cash').levels).total:null;return `<strong class="ob-big">${O.fmt(d.funded)}<small>funding if IMA signing slips 5 days</small></strong><ul>${line('warn','Paperwork and Ops setup turn red')}${cash?line('note',`Requirements view: ${cash[0]}–${cash[1]} business days`):''}</ul>`;}
  return '';}
 function board(){const s=O.schedule();
  return `<div class="ob-band"><strong>Funding forecast ${O.fmt(s.funded)} <em>+${s.funded-s.target} business days</em> <small>client target ${O.fmt(s.target)} · as of ${O.fmt(O.AS_OF)}</small></strong><div class="ob-lights">${s.stages.map(st=>ragChip(st.rag,st.short)).join('')}</div></div>
  <div class="ob-grid">${OUTS.map(([id,title,agents],i)=>`<button type="button" class="ob-card ${state.open===id?'sel':''}" data-st-open="${id}"><header><span class="ob-n">${i+1}</span><h3>${esc(title)}</h3></header>${by(agents)}<div class="ob-body">${summaryFor(id,s)}</div><span class="ob-more">Open →</span></button>`).join('')}</div>`;}
 function riskRegister(){const E=window.AGENT_DEMO;if(!E)return'';return `<section class="panel"><h3>Risk register handed over by the risk agents</h3><p class="smalltext">From the agent run on the 16 Sep evidence.</p>${E.risks('cash').map(r=>`<div class="ob-risk"><div class="split"><b>${r.id} · ${esc(r.title)}</b><span class="badge ${/High/.test(r.status)?'amber':'teal'}">${esc(r.status)}</span></div><p>${esc(r.fact)}</p><p><b>Recommended action:</b> ${esc(r.action)}</p>${cites(r.evidence.slice(0,3))}</div>`).join('')}</section>`;}
 function detail(id){const s0=O.schedule();
  if(id==='req')return requirementsTable();
  if(id==='oblig')return obligationsPane();
  if(id==='risk')return issues(s0)+riskRegister();
  if(id==='plan')return `${summary(s0)}${stageStrip(s0)}<section class="panel st-main"><div class="st-tasks"><div>${taskTable(s0)}</div>${taskDetail(s0)}</div></section>`;
  if(id==='players')return whoActs(s0)+playersTable(s0);
  return `<h3 class="ob-sub">If a task slips</h3><section class="panel st-main">${depsPane(sched())}</section><h3 class="ob-sub">If the client’s requirements change</h3><p class="smalltext">Set each requirement area to Low, Medium or High to see the onboarding days, each issue’s impact and who does what. Starts from the evidence snapshot selected at the top (14–16 Sep).</p><div id="wr-root" class="wrc"></div>`;}
 function drawer(){const i=OUTS.findIndex(o=>o[0]===state.open),[id,title,agents]=OUTS[i],prev=OUTS[i-1],next=OUTS[i+1];
  return `<div class="ob-backdrop" data-st-close></div><aside class="ob-drawer" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="ob-dhead"><div class="ob-dtitle"><span class="ob-n">${i+1}</span><div><h2>${esc(title)}</h2>${by(agents)}</div></div><div class="ob-dnav">${prev?`<button type="button" class="btn small" data-st-open="${prev[0]}">← ${esc(prev[1])}</button>`:''}<span>${i+1} of ${OUTS.length}</span>${next?`<button type="button" class="btn small primary" data-st-open="${next[0]}">Next: ${esc(next[1])} →</button>`:`<button type="button" class="btn small primary" data-st-close>Back to all outputs</button>`}<button type="button" class="ob-x" data-st-close aria-label="Close">×</button></div></header><div class="ob-dbody">${detail(id)}</div></aside>`;}
 /* ---------- Leadership view ---------- */
 function leadership(){const B=O.book(),late=B.filter(x=>x.slip>0),red=B.filter(x=>x.rag==='red'),amber=B.filter(x=>x.rag==='amber'),aum=B.reduce((t,x)=>t+x.aum,0),soon=B.filter(x=>x.target-O.AS_OF<=30&&x.stage<4);
  const bar=(items,key,labels)=>{const max=Math.max(...Object.keys(labels).map(k=>items.filter(x=>x[key]===k).length));return Object.entries(labels).map(([k,l])=>{const xs=items.filter(x=>x[key]==k),n=xs.length;return `<div class="st-bar-row"><span>${esc(l)}</span><div class="st-bar" title="${esc(l)}: ${n} in flight · ${xs.filter(x=>x.rag==='red').length} off track · ${xs.filter(x=>x.rag==='amber').length} at risk">${['red','amber','green','grey'].map(r=>{const c=xs.filter(x=>x.rag===r).length;return c?`<i class="st-${r}" style="width:${c/max*100}%"></i>`:'';}).join('')}</div><b>${n}</b></div>`;}).join('');};
  const stages=O.STAGES.map((st,i)=>{const xs=B.filter(x=>x.stage===i);return {st,n:xs.length,bad:xs.filter(x=>x.rag!=='green').length,red:xs.filter(x=>x.rag==='red').length};}),neck=[...stages].sort((a,b)=>b.bad-a.bad||b.red-a.red)[0];
  const risks=['Contracts','Investment restrictions','Funding','Reporting','AML/KYC','Billing'],vs=['sa','cit','mf'],cell=(r,v)=>B.filter(x=>x.risk===r&&x.vehicle===v&&x.rag!=='green').length,mx=Math.max(1,...risks.flatMap(r=>vs.map(v=>cell(r,v))));
  const waits=Object.entries(B.filter(x=>x.rag!=='green').reduce((t,x)=>(t[x.waiting]=(t[x.waiting]||0)+1,t),{})).sort((a,b)=>b[1]-a[1]);
  return `<div class="st-lead"><div class="eyebrow">As of ${O.fmt(O.AS_OF)} 2026</div>
  <div class="metrics st-lead-kpis"><div class="metric"><strong>${B.length}</strong><span>Onboardings in flight</span></div><div class="metric"><strong>$${(aum/1000).toFixed(1)}bn</strong><span>Assets in flight</span></div><div class="metric"><strong>${late.length}</strong><span>Behind schedule</span></div><div class="metric"><strong>${red.length} <small>off track</small> · ${amber.length} <small>at risk</small></strong><span>Need attention</span></div><div class="metric"><strong>${soon.length}</strong><span>Due to fund within 30 business days</span></div></div>
  <div class="st-lead-grid"><section class="panel"><h3>By vehicle</h3>${bar(B,'vehicle',VEH)}<h3 style="margin-top:18px">By client type</h3>${bar(B,'relationship',REL)}<p class="st-key">${['red','amber','green'].map(r=>ragChip(r)).join(' ')}</p></section>
  <section class="panel"><h3>Where onboardings sit, and the bottleneck</h3><div class="st-funnel">${stages.map(x=>`<div class="st-funnel-col ${x===neck?'neck':''}"><b>${x.n}</b><div class="st-funnel-bar"><i style="height:${x.n/Math.max(...stages.map(y=>y.n))*100}%"></i></div><span>${esc(x.st.name)}</span><small>${x.bad?`${x.bad} need attention`:'All on track'}</small></div>`).join('')}</div><p class="smalltext"><b>Bottleneck: ${esc(neck.st.name)}.</b> ${neck.bad} of ${neck.n} onboardings there are at risk or off track. Teams most often waited on: ${waits.slice(0,3).map(([t,n])=>`${esc(O.TEAMS[t])} (${n})`).join(', ')}.</p></section>
  <section class="panel"><h3>Risk concentration</h3><p class="smalltext">At-risk or off-track onboardings by main risk area and vehicle.</p><table class="st-heat"><thead><tr><th>Risk area</th>${vs.map(v=>`<th>${VEH[v]}</th>`).join('')}</tr></thead><tbody>${risks.map(r=>`<tr><td>${r}</td>${vs.map(v=>{const n=cell(r,v);return `<td><span class="st-heat-cell" style="--a:${n/mx}" title="${esc(r)} · ${VEH[v]}: ${n}">${n||'·'}</span></td>`;}).join('')}</tr>`).join('')}</tbody></table></section></div>
  <section class="panel"><h3>Behind schedule</h3><div class="tablewrap"><table class="st-table"><thead><tr><th>Client</th><th>Vehicle</th><th>Client type</th><th>Stage</th><th>Status</th><th>Target</th><th>Forecast</th><th>Main risk</th><th>Waiting on</th></tr></thead><tbody>${late.sort((a,b)=>b.slip-a.slip).map(x=>`<tr class="${x.live?'st-live':''}"><td><b>${esc(x.name)}</b>${x.live?' <button type="button" class="btn small primary" data-view="framework">See how we plan it →</button>':''}</td><td>${VEH[x.vehicle]}</td><td>${esc(REL[x.relationship])}</td><td>${esc(O.STAGES[x.stage].name)}</td><td>${ragChip(x.rag)}</td><td>${O.fmt(x.target)}</td><td><b class="bad">${O.fmt(x.target+x.slip)}</b> <small>+${x.slip}d</small></td><td>${esc(x.risk)}</td><td>${esc(O.TEAMS[x.waiting])}</td></tr>`).join('')}</tbody></table></div></section></div>`;}
 let disposeWr=null;
 function render(){const body=root.querySelector?.('.ob-dbody'),keep=body&&state.lastOpen===state.open?body.scrollTop:0;
  if(disposeWr){disposeWr();disposeWr=null;}
  root.innerHTML=state.page==='portfolio'?leadership():board()+(state.open?drawer():'');
  if(state.open==='whatif'&&opt.mountWorkflow){const el=root.querySelector('#wr-root');if(el)disposeWr=opt.mountWorkflow(el);}
  const nb=state.open&&root.querySelector?.('.ob-dbody');if(nb)nb.scrollTop=keep;
  state.lastOpen=state.open;document.body?.classList?.toggle('ob-lock',Boolean(state.open));}
 function onClick(e){const b=e.target.closest('button,[data-st-task],[data-st-close]');if(b&&b.dataset.view)return;if(!b||!root.contains(b)||b.dataset.source)return;const d=b.dataset;
  if(d.stOpen){state.open=d.stOpen;render();return;}
  if(d.stClose!==undefined){state.open=null;render();return;}
  if(d.stStage){state.stage=Number(d.stStage);const first=O.schedule().stages[state.stage].tasks.find(t=>!t.done)||O.schedule().stages[state.stage].tasks[0];state.task=first.id;render();return;}
  if(d.stSimDays){state.simDays=Number(d.stSimDays);render();return;}
  if(d.stSim){const t=O.TASKS.find(x=>x.id===d.stSim);if(t.done==null&&t.stage<4){state.simTask=t.id;if(!state.simDays)state.simDays=5;render();}return;}
  if(d.stTask){state.task=d.stTask;state.stage=O.TASKS.find(t=>t.id===d.stTask).stage;if(state.page==='output')state.open='plan';render();}}
 function onChange(e){if(e.target.hasAttribute?.('data-st-sim-task')){state.simTask=e.target.value;if(!state.simDays)state.simDays=5;render();}}
 function onKey(e){if(e.key==='Enter'&&e.target.dataset?.stTask){state.task=e.target.dataset.stTask;render();}}
 function onEsc(e){if(e.key==='Escape'&&state.open){state.open=null;render();}}
 render();root.addEventListener('click',onClick);root.addEventListener('change',onChange);root.addEventListener('keydown',onKey);document.addEventListener('keydown',onEsc);
 return ()=>{if(disposeWr)disposeWr();document.removeEventListener('keydown',onEsc);document.body?.classList?.remove('ob-lock');root.removeEventListener('click',onClick);root.removeEventListener('change',onChange);root.removeEventListener('keydown',onKey);};
}
window.SA_STATUS={markup,mount};
})();
